package com.med.info.mapper;

import com.med.info.domain.Miss_disease_department_mapping;

public interface Miss_disease_department_mappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_disease_department_mapping
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_disease_department_mapping
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int insert(Miss_disease_department_mapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_disease_department_mapping
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int insertSelective(Miss_disease_department_mapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_disease_department_mapping
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    Miss_disease_department_mapping selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_disease_department_mapping
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKeySelective(Miss_disease_department_mapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_disease_department_mapping
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Miss_disease_department_mapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_disease_department_mapping
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKey(Miss_disease_department_mapping record);
}