package com.med.info.mapper;

import com.med.info.domain.Miss_control_log;

public interface Miss_control_logMapper extends BaseMapper<Miss_control_log>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_log
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int deleteByPrimaryKey(String loginuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_log
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int insert(Miss_control_log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_log
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int insertSelective(Miss_control_log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_log
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    Miss_control_log selectByPrimaryKey(String loginuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_log
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKeySelective(Miss_control_log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_log
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKey(Miss_control_log record);
}