package com.med.info.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.med.info.domain.Miss_chinese_disease;
import com.med.info.domain.Miss_chinese_diseaseWithBLOBs;
import com.med.info.domain.Miss_institutionWithBLOBs;

public interface Miss_chinese_diseaseMapper extends BaseMapper<Miss_chinese_diseaseWithBLOBs>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_chinese_disease
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_chinese_disease
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    int insert(Miss_chinese_diseaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_chinese_disease
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    int insertSelective(Miss_chinese_diseaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_chinese_disease
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    Miss_chinese_diseaseWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_chinese_disease
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    int updateByPrimaryKeySelective(Miss_chinese_diseaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_chinese_disease
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Miss_chinese_diseaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_chinese_disease
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    int updateByPrimaryKey(Miss_chinese_disease record);
    
    List<Miss_chinese_diseaseWithBLOBs> check(@Param("chineseName") String chineseName, @Param("englishName") String englishName,  @Param("otherName") String otherName);
}