package com.med.info.mapper;

import java.util.List;

import com.med.info.domain.Miss_department;
import com.med.info.mapper.domain.DepartmentMapDTO;
import com.med.info.mapper.domain.InstitutionInfoDTO;
import org.apache.ibatis.annotations.Param;

public interface Miss_departmentMapper extends BaseMapper<Miss_department>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_department
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_department
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int insert(Miss_department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_department
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int insertSelective(Miss_department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_department
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    Miss_department selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_department
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKeySelective(Miss_department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_department
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Miss_department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_department
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKey(Miss_department record);
    
    List<DepartmentMapDTO> getDepartmentMapByIds(List<Long> ids);

	List<DepartmentMapDTO> getDepartmentMapByDoctorId(Long id);

	List<DepartmentMapDTO> getDepartmentMapByInstitutionId(Long id);
}