package com.med.info.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.med.info.domain.Miss_article;
import com.med.info.domain.Miss_articleWithBLOBs;

public interface Miss_articleMapper extends BaseMapper<Miss_articleWithBLOBs>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_article
     *
     * @mbg.generated Thu May 02 15:20:23 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_article
     *
     * @mbg.generated Thu May 02 15:20:23 CST 2019
     */
    int insert(Miss_articleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_article
     *
     * @mbg.generated Thu May 02 15:20:23 CST 2019
     */
    int insertSelective(Miss_articleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_article
     *
     * @mbg.generated Thu May 02 15:20:23 CST 2019
     */
    Miss_articleWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_article
     *
     * @mbg.generated Thu May 02 15:20:23 CST 2019
     */
    int updateByPrimaryKeySelective(Miss_articleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_article
     *
     * @mbg.generated Thu May 02 15:20:23 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Miss_articleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_article
     *
     * @mbg.generated Thu May 02 15:20:23 CST 2019
     */
    int updateByPrimaryKey(Miss_article record);
    
    List<Miss_articleWithBLOBs> check(@Param("title") String title, @Param("author") String author);
}