package com.med.info.mapper;

import com.med.info.domain.Miss_control_task_detail;
import com.med.info.domain.Miss_control_task_detailWithBLOBs;

public interface Miss_control_task_detailMapper extends BaseMapper<Miss_control_task_detail>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_task_detail
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int deleteByPrimaryKey(String taskuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_task_detail
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int insert(Miss_control_task_detailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_task_detail
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int insertSelective(Miss_control_task_detailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_task_detail
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    Miss_control_task_detailWithBLOBs selectByPrimaryKey(String taskuuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_task_detail
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKeySelective(Miss_control_task_detailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_task_detail
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Miss_control_task_detailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_task_detail
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKey(Miss_control_task_detail record);
}