package com.med.info.mapper;

import com.med.info.domain.Miss_control_userAndRole;

import java.util.List;

public interface Miss_control_userAndRoleMapper extends BaseMapper<Miss_control_userAndRole>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_userAndRole
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int deleteByPrimaryKey(String uruuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_userAndRole
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int insert(Miss_control_userAndRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_userAndRole
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int insertSelective(Miss_control_userAndRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_userAndRole
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    Miss_control_userAndRole selectByPrimaryKey(String uruuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_userAndRole
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKeySelective(Miss_control_userAndRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miss_control_userAndRole
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    int updateByPrimaryKey(Miss_control_userAndRole record);
    
    int deleteByUserCode(String usercode);

    List<Miss_control_userAndRole> selectByCode(Miss_control_userAndRole miss_control_userAndRole);
}