package com.med.info.domain;

import java.util.Date;

public class Miss_institution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.name
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.level
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.institution_district_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Long institutionDistrictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.address
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.nature
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String nature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.category
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.insurance
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String insurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.found_date
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String foundDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.manage_department
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String manageDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.telephone
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.website
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.publish_service
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String publishService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.dean
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String dean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.parent_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.refenrence
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String refenrence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.emergency_start_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Date emergencyStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.emergency_end_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Date emergencyEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.outpatient_start_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Date outpatientStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.outpatient_end_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Date outpatientEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.registration_start_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Date registrationStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.registration_end_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Date registrationEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.dataStatus
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String datastatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.task_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution.task_status
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String taskStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.id
     *
     * @return the value of miss_institution.id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.id
     *
     * @param id the value for miss_institution.id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.name
     *
     * @return the value of miss_institution.name
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.name
     *
     * @param name the value for miss_institution.name
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.level
     *
     * @return the value of miss_institution.level
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.level
     *
     * @param level the value for miss_institution.level
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.institution_district_id
     *
     * @return the value of miss_institution.institution_district_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Long getInstitutionDistrictId() {
        return institutionDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.institution_district_id
     *
     * @param institutionDistrictId the value for miss_institution.institution_district_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setInstitutionDistrictId(Long institutionDistrictId) {
        this.institutionDistrictId = institutionDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.address
     *
     * @return the value of miss_institution.address
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.address
     *
     * @param address the value for miss_institution.address
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.nature
     *
     * @return the value of miss_institution.nature
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.nature
     *
     * @param nature the value for miss_institution.nature
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setNature(String nature) {
        this.nature = nature == null ? null : nature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.category
     *
     * @return the value of miss_institution.category
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.category
     *
     * @param category the value for miss_institution.category
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.insurance
     *
     * @return the value of miss_institution.insurance
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getInsurance() {
        return insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.insurance
     *
     * @param insurance the value for miss_institution.insurance
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setInsurance(String insurance) {
        this.insurance = insurance == null ? null : insurance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.found_date
     *
     * @return the value of miss_institution.found_date
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getFoundDate() {
        return foundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.found_date
     *
     * @param foundDate the value for miss_institution.found_date
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setFoundDate(String foundDate) {
        this.foundDate = foundDate == null ? null : foundDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.manage_department
     *
     * @return the value of miss_institution.manage_department
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getManageDepartment() {
        return manageDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.manage_department
     *
     * @param manageDepartment the value for miss_institution.manage_department
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setManageDepartment(String manageDepartment) {
        this.manageDepartment = manageDepartment == null ? null : manageDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.telephone
     *
     * @return the value of miss_institution.telephone
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.telephone
     *
     * @param telephone the value for miss_institution.telephone
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.website
     *
     * @return the value of miss_institution.website
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.website
     *
     * @param website the value for miss_institution.website
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.publish_service
     *
     * @return the value of miss_institution.publish_service
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getPublishService() {
        return publishService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.publish_service
     *
     * @param publishService the value for miss_institution.publish_service
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setPublishService(String publishService) {
        this.publishService = publishService == null ? null : publishService.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.dean
     *
     * @return the value of miss_institution.dean
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getDean() {
        return dean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.dean
     *
     * @param dean the value for miss_institution.dean
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDean(String dean) {
        this.dean = dean == null ? null : dean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.parent_id
     *
     * @return the value of miss_institution.parent_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.parent_id
     *
     * @param parentId the value for miss_institution.parent_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.refenrence
     *
     * @return the value of miss_institution.refenrence
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getRefenrence() {
        return refenrence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.refenrence
     *
     * @param refenrence the value for miss_institution.refenrence
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setRefenrence(String refenrence) {
        this.refenrence = refenrence == null ? null : refenrence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.emergency_start_time
     *
     * @return the value of miss_institution.emergency_start_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Date getEmergencyStartTime() {
        return emergencyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.emergency_start_time
     *
     * @param emergencyStartTime the value for miss_institution.emergency_start_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setEmergencyStartTime(Date emergencyStartTime) {
        this.emergencyStartTime = emergencyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.emergency_end_time
     *
     * @return the value of miss_institution.emergency_end_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Date getEmergencyEndTime() {
        return emergencyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.emergency_end_time
     *
     * @param emergencyEndTime the value for miss_institution.emergency_end_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setEmergencyEndTime(Date emergencyEndTime) {
        this.emergencyEndTime = emergencyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.outpatient_start_time
     *
     * @return the value of miss_institution.outpatient_start_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Date getOutpatientStartTime() {
        return outpatientStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.outpatient_start_time
     *
     * @param outpatientStartTime the value for miss_institution.outpatient_start_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setOutpatientStartTime(Date outpatientStartTime) {
        this.outpatientStartTime = outpatientStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.outpatient_end_time
     *
     * @return the value of miss_institution.outpatient_end_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Date getOutpatientEndTime() {
        return outpatientEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.outpatient_end_time
     *
     * @param outpatientEndTime the value for miss_institution.outpatient_end_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setOutpatientEndTime(Date outpatientEndTime) {
        this.outpatientEndTime = outpatientEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.registration_start_time
     *
     * @return the value of miss_institution.registration_start_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Date getRegistrationStartTime() {
        return registrationStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.registration_start_time
     *
     * @param registrationStartTime the value for miss_institution.registration_start_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setRegistrationStartTime(Date registrationStartTime) {
        this.registrationStartTime = registrationStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.registration_end_time
     *
     * @return the value of miss_institution.registration_end_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Date getRegistrationEndTime() {
        return registrationEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.registration_end_time
     *
     * @param registrationEndTime the value for miss_institution.registration_end_time
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setRegistrationEndTime(Date registrationEndTime) {
        this.registrationEndTime = registrationEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.dataStatus
     *
     * @return the value of miss_institution.dataStatus
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getDatastatus() {
        return datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.dataStatus
     *
     * @param datastatus the value for miss_institution.dataStatus
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDatastatus(String datastatus) {
        this.datastatus = datastatus == null ? null : datastatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.task_id
     *
     * @return the value of miss_institution.task_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.task_id
     *
     * @param taskId the value for miss_institution.task_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution.task_status
     *
     * @return the value of miss_institution.task_status
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution.task_status
     *
     * @param taskStatus the value for miss_institution.task_status
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }
}