package com.med.info.domain;

public class Miss_department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_department.id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_department.department_code
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String departmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_department.department_name
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_department.level
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_department.parent_department_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Long parentDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_department.dataStatus
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String datastatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_department.task_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_department.task_status
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_department.task_json
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String taskJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_department.id
     *
     * @return the value of miss_department.id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_department.id
     *
     * @param id the value for miss_department.id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_department.department_code
     *
     * @return the value of miss_department.department_code
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_department.department_code
     *
     * @param departmentCode the value for miss_department.department_code
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_department.department_name
     *
     * @return the value of miss_department.department_name
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_department.department_name
     *
     * @param departmentName the value for miss_department.department_name
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_department.level
     *
     * @return the value of miss_department.level
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_department.level
     *
     * @param level the value for miss_department.level
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_department.parent_department_id
     *
     * @return the value of miss_department.parent_department_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Long getParentDepartmentId() {
        return parentDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_department.parent_department_id
     *
     * @param parentDepartmentId the value for miss_department.parent_department_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setParentDepartmentId(Long parentDepartmentId) {
        this.parentDepartmentId = parentDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_department.dataStatus
     *
     * @return the value of miss_department.dataStatus
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getDatastatus() {
        return datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_department.dataStatus
     *
     * @param datastatus the value for miss_department.dataStatus
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDatastatus(String datastatus) {
        this.datastatus = datastatus == null ? null : datastatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_department.task_id
     *
     * @return the value of miss_department.task_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_department.task_id
     *
     * @param taskId the value for miss_department.task_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_department.task_status
     *
     * @return the value of miss_department.task_status
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_department.task_status
     *
     * @param taskStatus the value for miss_department.task_status
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_department.task_json
     *
     * @return the value of miss_department.task_json
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getTaskJson() {
        return taskJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_department.task_json
     *
     * @param taskJson the value for miss_department.task_json
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setTaskJson(String taskJson) {
        this.taskJson = taskJson == null ? null : taskJson.trim();
    }
}