package com.med.info.domain;

public class Miss_control_roleAndAction extends BaseDomain{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_roleAndAction.RAuuid
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String rauuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_roleAndAction.roleCode
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String rolecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_roleAndAction.actionCode
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String actioncode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_roleAndAction.relationStatus
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String relationstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_roleAndAction.relationCreateDate
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String relationcreatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_roleAndAction.RAuuid
     *
     * @return the value of miss_control_roleAndAction.RAuuid
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getRauuid() {
        return rauuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_roleAndAction.RAuuid
     *
     * @param rauuid the value for miss_control_roleAndAction.RAuuid
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setRauuid(String rauuid) {
        this.rauuid = rauuid == null ? null : rauuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_roleAndAction.roleCode
     *
     * @return the value of miss_control_roleAndAction.roleCode
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_roleAndAction.roleCode
     *
     * @param rolecode the value for miss_control_roleAndAction.roleCode
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_roleAndAction.actionCode
     *
     * @return the value of miss_control_roleAndAction.actionCode
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getActioncode() {
        return actioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_roleAndAction.actionCode
     *
     * @param actioncode the value for miss_control_roleAndAction.actionCode
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setActioncode(String actioncode) {
        this.actioncode = actioncode == null ? null : actioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_roleAndAction.relationStatus
     *
     * @return the value of miss_control_roleAndAction.relationStatus
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getRelationstatus() {
        return relationstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_roleAndAction.relationStatus
     *
     * @param relationstatus the value for miss_control_roleAndAction.relationStatus
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setRelationstatus(String relationstatus) {
        this.relationstatus = relationstatus == null ? null : relationstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_roleAndAction.relationCreateDate
     *
     * @return the value of miss_control_roleAndAction.relationCreateDate
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getRelationcreatedate() {
        return relationcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_roleAndAction.relationCreateDate
     *
     * @param relationcreatedate the value for miss_control_roleAndAction.relationCreateDate
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setRelationcreatedate(String relationcreatedate) {
        this.relationcreatedate = relationcreatedate == null ? null : relationcreatedate.trim();
    }
}