package com.med.info.domain;

public class Miss_medicalWithBLOBs extends Miss_medical {
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.constitute
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String constitute;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.property
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String property;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.func
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String func;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.main_attend
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String mainAttend;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.standard
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String standard;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.pharmacology
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String pharmacology;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.toxicological_effects
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String toxicologicalEffects;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.clinical_application
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String clinicalApplication;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.adverse_reactions
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String adverseReactions;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.taboo
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String taboo;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.notice
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String notice;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.identify
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String identify;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.pharmacy_check
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String pharmacyCheck;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.content_pic
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String contentPic;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.medic_format
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String medicFormat;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.notes
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String notes;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.component
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String component;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.main_meffect
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String mainMeffect;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.analyze
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String analyze;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.interactions
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String interactions;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.history
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String history;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.drug_introduce
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String drugIntroduce;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.awards
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String awards;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.research
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String research;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.monograph
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String monograph;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.message_from
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String messageFrom;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.product_info
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String productInfo;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.indication
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String indication;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.dosage
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String dosage;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.introduction
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String introduction;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.task_json
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String taskJson;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.gravida_durg
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String gravidaDurg;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.children_durg
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String childrenDurg;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.elderly_durg
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String elderlyDurg;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.durg_overdose
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String durgOverdose;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.miss_medicalcol
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String missMedicalcol;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.pharmacokinetics
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String pharmacokinetics;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.combined_medication
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String combinedMedication;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.physician_advice
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String physicianAdvice;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.route_administration
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String routeAdministration;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.dosage_form
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String dosageForm;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.functional_classification
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String functionalClassification;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.disease_classification
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String diseaseClassification;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.thumbnail
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String thumbnail;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column miss_medical.adaptation
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   private String adaptation;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.constitute
    *
    * @return the value of miss_medical.constitute
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getConstitute() {
       return constitute;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.constitute
    *
    * @param constitute the value for miss_medical.constitute
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setConstitute(String constitute) {
       this.constitute = constitute == null ? null : constitute.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.property
    *
    * @return the value of miss_medical.property
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getProperty() {
       return property;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.property
    *
    * @param property the value for miss_medical.property
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setProperty(String property) {
       this.property = property == null ? null : property.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.func
    *
    * @return the value of miss_medical.func
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getFunc() {
       return func;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.func
    *
    * @param func the value for miss_medical.func
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setFunc(String func) {
       this.func = func == null ? null : func.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.main_attend
    *
    * @return the value of miss_medical.main_attend
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getMainAttend() {
       return mainAttend;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.main_attend
    *
    * @param mainAttend the value for miss_medical.main_attend
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setMainAttend(String mainAttend) {
       this.mainAttend = mainAttend == null ? null : mainAttend.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.standard
    *
    * @return the value of miss_medical.standard
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getStandard() {
       return standard;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.standard
    *
    * @param standard the value for miss_medical.standard
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setStandard(String standard) {
       this.standard = standard == null ? null : standard.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.pharmacology
    *
    * @return the value of miss_medical.pharmacology
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getPharmacology() {
       return pharmacology;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.pharmacology
    *
    * @param pharmacology the value for miss_medical.pharmacology
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setPharmacology(String pharmacology) {
       this.pharmacology = pharmacology == null ? null : pharmacology.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.toxicological_effects
    *
    * @return the value of miss_medical.toxicological_effects
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getToxicologicalEffects() {
       return toxicologicalEffects;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.toxicological_effects
    *
    * @param toxicologicalEffects the value for miss_medical.toxicological_effects
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setToxicologicalEffects(String toxicologicalEffects) {
       this.toxicologicalEffects = toxicologicalEffects == null ? null : toxicologicalEffects.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.clinical_application
    *
    * @return the value of miss_medical.clinical_application
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getClinicalApplication() {
       return clinicalApplication;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.clinical_application
    *
    * @param clinicalApplication the value for miss_medical.clinical_application
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setClinicalApplication(String clinicalApplication) {
       this.clinicalApplication = clinicalApplication == null ? null : clinicalApplication.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.adverse_reactions
    *
    * @return the value of miss_medical.adverse_reactions
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getAdverseReactions() {
       return adverseReactions;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.adverse_reactions
    *
    * @param adverseReactions the value for miss_medical.adverse_reactions
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setAdverseReactions(String adverseReactions) {
       this.adverseReactions = adverseReactions == null ? null : adverseReactions.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.taboo
    *
    * @return the value of miss_medical.taboo
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getTaboo() {
       return taboo;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.taboo
    *
    * @param taboo the value for miss_medical.taboo
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setTaboo(String taboo) {
       this.taboo = taboo == null ? null : taboo.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.notice
    *
    * @return the value of miss_medical.notice
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getNotice() {
       return notice;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.notice
    *
    * @param notice the value for miss_medical.notice
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setNotice(String notice) {
       this.notice = notice == null ? null : notice.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.identify
    *
    * @return the value of miss_medical.identify
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getIdentify() {
       return identify;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.identify
    *
    * @param identify the value for miss_medical.identify
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setIdentify(String identify) {
       this.identify = identify == null ? null : identify.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.pharmacy_check
    *
    * @return the value of miss_medical.pharmacy_check
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getPharmacyCheck() {
       return pharmacyCheck;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.pharmacy_check
    *
    * @param pharmacyCheck the value for miss_medical.pharmacy_check
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setPharmacyCheck(String pharmacyCheck) {
       this.pharmacyCheck = pharmacyCheck == null ? null : pharmacyCheck.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.content_pic
    *
    * @return the value of miss_medical.content_pic
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getContentPic() {
       return contentPic;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.content_pic
    *
    * @param contentPic the value for miss_medical.content_pic
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setContentPic(String contentPic) {
       this.contentPic = contentPic == null ? null : contentPic.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.medic_format
    *
    * @return the value of miss_medical.medic_format
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getMedicFormat() {
       return medicFormat;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.medic_format
    *
    * @param medicFormat the value for miss_medical.medic_format
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setMedicFormat(String medicFormat) {
       this.medicFormat = medicFormat == null ? null : medicFormat.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.notes
    *
    * @return the value of miss_medical.notes
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getNotes() {
       return notes;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.notes
    *
    * @param notes the value for miss_medical.notes
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setNotes(String notes) {
       this.notes = notes == null ? null : notes.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.component
    *
    * @return the value of miss_medical.component
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getComponent() {
       return component;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.component
    *
    * @param component the value for miss_medical.component
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setComponent(String component) {
       this.component = component == null ? null : component.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.main_meffect
    *
    * @return the value of miss_medical.main_meffect
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getMainMeffect() {
       return mainMeffect;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.main_meffect
    *
    * @param mainMeffect the value for miss_medical.main_meffect
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setMainMeffect(String mainMeffect) {
       this.mainMeffect = mainMeffect == null ? null : mainMeffect.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.analyze
    *
    * @return the value of miss_medical.analyze
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getAnalyze() {
       return analyze;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.analyze
    *
    * @param analyze the value for miss_medical.analyze
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setAnalyze(String analyze) {
       this.analyze = analyze == null ? null : analyze.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.interactions
    *
    * @return the value of miss_medical.interactions
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getInteractions() {
       return interactions;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.interactions
    *
    * @param interactions the value for miss_medical.interactions
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setInteractions(String interactions) {
       this.interactions = interactions == null ? null : interactions.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.history
    *
    * @return the value of miss_medical.history
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getHistory() {
       return history;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.history
    *
    * @param history the value for miss_medical.history
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setHistory(String history) {
       this.history = history == null ? null : history.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.drug_introduce
    *
    * @return the value of miss_medical.drug_introduce
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getDrugIntroduce() {
       return drugIntroduce;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.drug_introduce
    *
    * @param drugIntroduce the value for miss_medical.drug_introduce
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setDrugIntroduce(String drugIntroduce) {
       this.drugIntroduce = drugIntroduce == null ? null : drugIntroduce.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.awards
    *
    * @return the value of miss_medical.awards
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getAwards() {
       return awards;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.awards
    *
    * @param awards the value for miss_medical.awards
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setAwards(String awards) {
       this.awards = awards == null ? null : awards.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.research
    *
    * @return the value of miss_medical.research
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getResearch() {
       return research;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.research
    *
    * @param research the value for miss_medical.research
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setResearch(String research) {
       this.research = research == null ? null : research.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.monograph
    *
    * @return the value of miss_medical.monograph
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getMonograph() {
       return monograph;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.monograph
    *
    * @param monograph the value for miss_medical.monograph
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setMonograph(String monograph) {
       this.monograph = monograph == null ? null : monograph.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.message_from
    *
    * @return the value of miss_medical.message_from
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getMessageFrom() {
       return messageFrom;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.message_from
    *
    * @param messageFrom the value for miss_medical.message_from
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setMessageFrom(String messageFrom) {
       this.messageFrom = messageFrom == null ? null : messageFrom.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.product_info
    *
    * @return the value of miss_medical.product_info
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getProductInfo() {
       return productInfo;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.product_info
    *
    * @param productInfo the value for miss_medical.product_info
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setProductInfo(String productInfo) {
       this.productInfo = productInfo == null ? null : productInfo.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.indication
    *
    * @return the value of miss_medical.indication
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getIndication() {
       return indication;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.indication
    *
    * @param indication the value for miss_medical.indication
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setIndication(String indication) {
       this.indication = indication == null ? null : indication.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.dosage
    *
    * @return the value of miss_medical.dosage
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getDosage() {
       return dosage;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.dosage
    *
    * @param dosage the value for miss_medical.dosage
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setDosage(String dosage) {
       this.dosage = dosage == null ? null : dosage.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.introduction
    *
    * @return the value of miss_medical.introduction
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getIntroduction() {
       return introduction;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.introduction
    *
    * @param introduction the value for miss_medical.introduction
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setIntroduction(String introduction) {
       this.introduction = introduction == null ? null : introduction.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.task_json
    *
    * @return the value of miss_medical.task_json
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getTaskJson() {
       return taskJson;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.task_json
    *
    * @param taskJson the value for miss_medical.task_json
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setTaskJson(String taskJson) {
       this.taskJson = taskJson == null ? null : taskJson.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.gravida_durg
    *
    * @return the value of miss_medical.gravida_durg
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getGravidaDurg() {
       return gravidaDurg;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.gravida_durg
    *
    * @param gravidaDurg the value for miss_medical.gravida_durg
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setGravidaDurg(String gravidaDurg) {
       this.gravidaDurg = gravidaDurg == null ? null : gravidaDurg.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.children_durg
    *
    * @return the value of miss_medical.children_durg
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getChildrenDurg() {
       return childrenDurg;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.children_durg
    *
    * @param childrenDurg the value for miss_medical.children_durg
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setChildrenDurg(String childrenDurg) {
       this.childrenDurg = childrenDurg == null ? null : childrenDurg.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.elderly_durg
    *
    * @return the value of miss_medical.elderly_durg
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getElderlyDurg() {
       return elderlyDurg;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.elderly_durg
    *
    * @param elderlyDurg the value for miss_medical.elderly_durg
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setElderlyDurg(String elderlyDurg) {
       this.elderlyDurg = elderlyDurg == null ? null : elderlyDurg.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.durg_overdose
    *
    * @return the value of miss_medical.durg_overdose
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getDurgOverdose() {
       return durgOverdose;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.durg_overdose
    *
    * @param durgOverdose the value for miss_medical.durg_overdose
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setDurgOverdose(String durgOverdose) {
       this.durgOverdose = durgOverdose == null ? null : durgOverdose.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.miss_medicalcol
    *
    * @return the value of miss_medical.miss_medicalcol
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getMissMedicalcol() {
       return missMedicalcol;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.miss_medicalcol
    *
    * @param missMedicalcol the value for miss_medical.miss_medicalcol
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setMissMedicalcol(String missMedicalcol) {
       this.missMedicalcol = missMedicalcol == null ? null : missMedicalcol.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.pharmacokinetics
    *
    * @return the value of miss_medical.pharmacokinetics
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getPharmacokinetics() {
       return pharmacokinetics;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.pharmacokinetics
    *
    * @param pharmacokinetics the value for miss_medical.pharmacokinetics
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setPharmacokinetics(String pharmacokinetics) {
       this.pharmacokinetics = pharmacokinetics == null ? null : pharmacokinetics.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.combined_medication
    *
    * @return the value of miss_medical.combined_medication
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getCombinedMedication() {
       return combinedMedication;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.combined_medication
    *
    * @param combinedMedication the value for miss_medical.combined_medication
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setCombinedMedication(String combinedMedication) {
       this.combinedMedication = combinedMedication == null ? null : combinedMedication.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.physician_advice
    *
    * @return the value of miss_medical.physician_advice
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getPhysicianAdvice() {
       return physicianAdvice;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.physician_advice
    *
    * @param physicianAdvice the value for miss_medical.physician_advice
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setPhysicianAdvice(String physicianAdvice) {
       this.physicianAdvice = physicianAdvice == null ? null : physicianAdvice.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.route_administration
    *
    * @return the value of miss_medical.route_administration
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getRouteAdministration() {
       return routeAdministration;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.route_administration
    *
    * @param routeAdministration the value for miss_medical.route_administration
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setRouteAdministration(String routeAdministration) {
       this.routeAdministration = routeAdministration == null ? null : routeAdministration.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.dosage_form
    *
    * @return the value of miss_medical.dosage_form
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getDosageForm() {
       return dosageForm;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.dosage_form
    *
    * @param dosageForm the value for miss_medical.dosage_form
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setDosageForm(String dosageForm) {
       this.dosageForm = dosageForm == null ? null : dosageForm.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.functional_classification
    *
    * @return the value of miss_medical.functional_classification
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getFunctionalClassification() {
       return functionalClassification;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.functional_classification
    *
    * @param functionalClassification the value for miss_medical.functional_classification
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setFunctionalClassification(String functionalClassification) {
       this.functionalClassification = functionalClassification == null ? null : functionalClassification.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.disease_classification
    *
    * @return the value of miss_medical.disease_classification
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getDiseaseClassification() {
       return diseaseClassification;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.disease_classification
    *
    * @param diseaseClassification the value for miss_medical.disease_classification
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setDiseaseClassification(String diseaseClassification) {
       this.diseaseClassification = diseaseClassification == null ? null : diseaseClassification.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.thumbnail
    *
    * @return the value of miss_medical.thumbnail
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getThumbnail() {
       return thumbnail;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.thumbnail
    *
    * @param thumbnail the value for miss_medical.thumbnail
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setThumbnail(String thumbnail) {
       this.thumbnail = thumbnail == null ? null : thumbnail.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column miss_medical.adaptation
    *
    * @return the value of miss_medical.adaptation
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public String getAdaptation() {
       return adaptation;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column miss_medical.adaptation
    *
    * @param adaptation the value for miss_medical.adaptation
    *
    * @mbg.generated Sat Apr 27 19:22:50 CST 2019
    */
   public void setAdaptation(String adaptation) {
       this.adaptation = adaptation == null ? null : adaptation.trim();
   }
}