package com.med.info.domain;

public class Miss_combination_diseaseWithBLOBs extends Miss_combination_disease {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.epidemiology
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String epidemiology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.t_related_diseases
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String tRelatedDiseases;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.etiology_pathogenesis
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String etiologyPathogenesis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.pathology
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String pathology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.clinical_types_class
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String clinicalTypesClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.clinical_manifestation
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String clinicalManifestation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.symptom
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String symptom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.sign
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.laboratory_examination
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String laboratoryExamination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.text_other_check
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String textOtherCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.diagnostic_points
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String diagnosticPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.differential_diagnosis
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String differentialDiagnosis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.prevention_treatment
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String preventionTreatment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.treatment_prognosis
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String treatmentPrognosis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.management
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String management;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.preventive_nursing
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String preventiveNursing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.nursing
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String nursing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.prevention_measures
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String preventionMeasures;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.modern_research
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String modernResearch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.drug_resistance
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String drugResistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.dietary_conditioning
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String dietaryConditioning;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.attention_matter
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String attentionMatter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_combination_disease.data_reference
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String dataReference;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.epidemiology
     *
     * @return the value of miss_combination_disease.epidemiology
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getEpidemiology() {
        return epidemiology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.epidemiology
     *
     * @param epidemiology the value for miss_combination_disease.epidemiology
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setEpidemiology(String epidemiology) {
        this.epidemiology = epidemiology == null ? null : epidemiology.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.t_related_diseases
     *
     * @return the value of miss_combination_disease.t_related_diseases
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String gettRelatedDiseases() {
        return tRelatedDiseases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.t_related_diseases
     *
     * @param tRelatedDiseases the value for miss_combination_disease.t_related_diseases
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void settRelatedDiseases(String tRelatedDiseases) {
        this.tRelatedDiseases = tRelatedDiseases == null ? null : tRelatedDiseases.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.etiology_pathogenesis
     *
     * @return the value of miss_combination_disease.etiology_pathogenesis
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getEtiologyPathogenesis() {
        return etiologyPathogenesis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.etiology_pathogenesis
     *
     * @param etiologyPathogenesis the value for miss_combination_disease.etiology_pathogenesis
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setEtiologyPathogenesis(String etiologyPathogenesis) {
        this.etiologyPathogenesis = etiologyPathogenesis == null ? null : etiologyPathogenesis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.pathology
     *
     * @return the value of miss_combination_disease.pathology
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getPathology() {
        return pathology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.pathology
     *
     * @param pathology the value for miss_combination_disease.pathology
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setPathology(String pathology) {
        this.pathology = pathology == null ? null : pathology.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.clinical_types_class
     *
     * @return the value of miss_combination_disease.clinical_types_class
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getClinicalTypesClass() {
        return clinicalTypesClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.clinical_types_class
     *
     * @param clinicalTypesClass the value for miss_combination_disease.clinical_types_class
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setClinicalTypesClass(String clinicalTypesClass) {
        this.clinicalTypesClass = clinicalTypesClass == null ? null : clinicalTypesClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.clinical_manifestation
     *
     * @return the value of miss_combination_disease.clinical_manifestation
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getClinicalManifestation() {
        return clinicalManifestation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.clinical_manifestation
     *
     * @param clinicalManifestation the value for miss_combination_disease.clinical_manifestation
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setClinicalManifestation(String clinicalManifestation) {
        this.clinicalManifestation = clinicalManifestation == null ? null : clinicalManifestation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.symptom
     *
     * @return the value of miss_combination_disease.symptom
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.symptom
     *
     * @param symptom the value for miss_combination_disease.symptom
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.sign
     *
     * @return the value of miss_combination_disease.sign
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.sign
     *
     * @param sign the value for miss_combination_disease.sign
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.laboratory_examination
     *
     * @return the value of miss_combination_disease.laboratory_examination
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getLaboratoryExamination() {
        return laboratoryExamination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.laboratory_examination
     *
     * @param laboratoryExamination the value for miss_combination_disease.laboratory_examination
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setLaboratoryExamination(String laboratoryExamination) {
        this.laboratoryExamination = laboratoryExamination == null ? null : laboratoryExamination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.text_other_check
     *
     * @return the value of miss_combination_disease.text_other_check
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getTextOtherCheck() {
        return textOtherCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.text_other_check
     *
     * @param textOtherCheck the value for miss_combination_disease.text_other_check
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setTextOtherCheck(String textOtherCheck) {
        this.textOtherCheck = textOtherCheck == null ? null : textOtherCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.diagnostic_points
     *
     * @return the value of miss_combination_disease.diagnostic_points
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getDiagnosticPoints() {
        return diagnosticPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.diagnostic_points
     *
     * @param diagnosticPoints the value for miss_combination_disease.diagnostic_points
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDiagnosticPoints(String diagnosticPoints) {
        this.diagnosticPoints = diagnosticPoints == null ? null : diagnosticPoints.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.differential_diagnosis
     *
     * @return the value of miss_combination_disease.differential_diagnosis
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getDifferentialDiagnosis() {
        return differentialDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.differential_diagnosis
     *
     * @param differentialDiagnosis the value for miss_combination_disease.differential_diagnosis
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDifferentialDiagnosis(String differentialDiagnosis) {
        this.differentialDiagnosis = differentialDiagnosis == null ? null : differentialDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.prevention_treatment
     *
     * @return the value of miss_combination_disease.prevention_treatment
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getPreventionTreatment() {
        return preventionTreatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.prevention_treatment
     *
     * @param preventionTreatment the value for miss_combination_disease.prevention_treatment
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setPreventionTreatment(String preventionTreatment) {
        this.preventionTreatment = preventionTreatment == null ? null : preventionTreatment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.treatment_prognosis
     *
     * @return the value of miss_combination_disease.treatment_prognosis
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getTreatmentPrognosis() {
        return treatmentPrognosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.treatment_prognosis
     *
     * @param treatmentPrognosis the value for miss_combination_disease.treatment_prognosis
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setTreatmentPrognosis(String treatmentPrognosis) {
        this.treatmentPrognosis = treatmentPrognosis == null ? null : treatmentPrognosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.management
     *
     * @return the value of miss_combination_disease.management
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getManagement() {
        return management;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.management
     *
     * @param management the value for miss_combination_disease.management
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setManagement(String management) {
        this.management = management == null ? null : management.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.preventive_nursing
     *
     * @return the value of miss_combination_disease.preventive_nursing
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getPreventiveNursing() {
        return preventiveNursing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.preventive_nursing
     *
     * @param preventiveNursing the value for miss_combination_disease.preventive_nursing
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setPreventiveNursing(String preventiveNursing) {
        this.preventiveNursing = preventiveNursing == null ? null : preventiveNursing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.nursing
     *
     * @return the value of miss_combination_disease.nursing
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getNursing() {
        return nursing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.nursing
     *
     * @param nursing the value for miss_combination_disease.nursing
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setNursing(String nursing) {
        this.nursing = nursing == null ? null : nursing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.prevention_measures
     *
     * @return the value of miss_combination_disease.prevention_measures
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getPreventionMeasures() {
        return preventionMeasures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.prevention_measures
     *
     * @param preventionMeasures the value for miss_combination_disease.prevention_measures
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setPreventionMeasures(String preventionMeasures) {
        this.preventionMeasures = preventionMeasures == null ? null : preventionMeasures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.modern_research
     *
     * @return the value of miss_combination_disease.modern_research
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getModernResearch() {
        return modernResearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.modern_research
     *
     * @param modernResearch the value for miss_combination_disease.modern_research
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setModernResearch(String modernResearch) {
        this.modernResearch = modernResearch == null ? null : modernResearch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.drug_resistance
     *
     * @return the value of miss_combination_disease.drug_resistance
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getDrugResistance() {
        return drugResistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.drug_resistance
     *
     * @param drugResistance the value for miss_combination_disease.drug_resistance
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDrugResistance(String drugResistance) {
        this.drugResistance = drugResistance == null ? null : drugResistance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.dietary_conditioning
     *
     * @return the value of miss_combination_disease.dietary_conditioning
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getDietaryConditioning() {
        return dietaryConditioning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.dietary_conditioning
     *
     * @param dietaryConditioning the value for miss_combination_disease.dietary_conditioning
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDietaryConditioning(String dietaryConditioning) {
        this.dietaryConditioning = dietaryConditioning == null ? null : dietaryConditioning.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.attention_matter
     *
     * @return the value of miss_combination_disease.attention_matter
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getAttentionMatter() {
        return attentionMatter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.attention_matter
     *
     * @param attentionMatter the value for miss_combination_disease.attention_matter
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setAttentionMatter(String attentionMatter) {
        this.attentionMatter = attentionMatter == null ? null : attentionMatter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_combination_disease.data_reference
     *
     * @return the value of miss_combination_disease.data_reference
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getDataReference() {
        return dataReference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_combination_disease.data_reference
     *
     * @param dataReference the value for miss_combination_disease.data_reference
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDataReference(String dataReference) {
        this.dataReference = dataReference == null ? null : dataReference.trim();
    }

}