package com.med.info.domain;

public class Miss_symptomWithBLOBs extends Miss_symptom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.t_other_therapies
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String tOtherTherapies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.common_diseases
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String commonDiseases;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.t_preventive_nursing
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String tPreventiveNursing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.syndrome
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String syndrome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.data_reference
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String dataReference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.chinese_medicine
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String chineseMedicine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.pathogeny
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String pathogeny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.pathogenesis
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String pathogenesis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.dialectical_points
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String dialecticalPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.symptom_analysis
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String symptomAnalysis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.common_chinese_medicine
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String commonChineseMedicine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.t_common_syndrome_types
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String tCommonSyndromeTypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.symptom_origin
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String symptomOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.task_json
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String taskJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.t_other_therapies
     *
     * @return the value of miss_symptom.t_other_therapies
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String gettOtherTherapies() {
        return tOtherTherapies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.t_other_therapies
     *
     * @param tOtherTherapies the value for miss_symptom.t_other_therapies
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void settOtherTherapies(String tOtherTherapies) {
        this.tOtherTherapies = tOtherTherapies == null ? null : tOtherTherapies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.common_diseases
     *
     * @return the value of miss_symptom.common_diseases
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getCommonDiseases() {
        return commonDiseases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.common_diseases
     *
     * @param commonDiseases the value for miss_symptom.common_diseases
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setCommonDiseases(String commonDiseases) {
        this.commonDiseases = commonDiseases == null ? null : commonDiseases.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.t_preventive_nursing
     *
     * @return the value of miss_symptom.t_preventive_nursing
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String gettPreventiveNursing() {
        return tPreventiveNursing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.t_preventive_nursing
     *
     * @param tPreventiveNursing the value for miss_symptom.t_preventive_nursing
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void settPreventiveNursing(String tPreventiveNursing) {
        this.tPreventiveNursing = tPreventiveNursing == null ? null : tPreventiveNursing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.syndrome
     *
     * @return the value of miss_symptom.syndrome
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getSyndrome() {
        return syndrome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.syndrome
     *
     * @param syndrome the value for miss_symptom.syndrome
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setSyndrome(String syndrome) {
        this.syndrome = syndrome == null ? null : syndrome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.data_reference
     *
     * @return the value of miss_symptom.data_reference
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getDataReference() {
        return dataReference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.data_reference
     *
     * @param dataReference the value for miss_symptom.data_reference
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setDataReference(String dataReference) {
        this.dataReference = dataReference == null ? null : dataReference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.chinese_medicine
     *
     * @return the value of miss_symptom.chinese_medicine
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getChineseMedicine() {
        return chineseMedicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.chinese_medicine
     *
     * @param chineseMedicine the value for miss_symptom.chinese_medicine
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setChineseMedicine(String chineseMedicine) {
        this.chineseMedicine = chineseMedicine == null ? null : chineseMedicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.pathogeny
     *
     * @return the value of miss_symptom.pathogeny
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getPathogeny() {
        return pathogeny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.pathogeny
     *
     * @param pathogeny the value for miss_symptom.pathogeny
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setPathogeny(String pathogeny) {
        this.pathogeny = pathogeny == null ? null : pathogeny.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.pathogenesis
     *
     * @return the value of miss_symptom.pathogenesis
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getPathogenesis() {
        return pathogenesis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.pathogenesis
     *
     * @param pathogenesis the value for miss_symptom.pathogenesis
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setPathogenesis(String pathogenesis) {
        this.pathogenesis = pathogenesis == null ? null : pathogenesis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.dialectical_points
     *
     * @return the value of miss_symptom.dialectical_points
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getDialecticalPoints() {
        return dialecticalPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.dialectical_points
     *
     * @param dialecticalPoints the value for miss_symptom.dialectical_points
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setDialecticalPoints(String dialecticalPoints) {
        this.dialecticalPoints = dialecticalPoints == null ? null : dialecticalPoints.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.symptom_analysis
     *
     * @return the value of miss_symptom.symptom_analysis
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getSymptomAnalysis() {
        return symptomAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.symptom_analysis
     *
     * @param symptomAnalysis the value for miss_symptom.symptom_analysis
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setSymptomAnalysis(String symptomAnalysis) {
        this.symptomAnalysis = symptomAnalysis == null ? null : symptomAnalysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.common_chinese_medicine
     *
     * @return the value of miss_symptom.common_chinese_medicine
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getCommonChineseMedicine() {
        return commonChineseMedicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.common_chinese_medicine
     *
     * @param commonChineseMedicine the value for miss_symptom.common_chinese_medicine
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setCommonChineseMedicine(String commonChineseMedicine) {
        this.commonChineseMedicine = commonChineseMedicine == null ? null : commonChineseMedicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.t_common_syndrome_types
     *
     * @return the value of miss_symptom.t_common_syndrome_types
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String gettCommonSyndromeTypes() {
        return tCommonSyndromeTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.t_common_syndrome_types
     *
     * @param tCommonSyndromeTypes the value for miss_symptom.t_common_syndrome_types
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void settCommonSyndromeTypes(String tCommonSyndromeTypes) {
        this.tCommonSyndromeTypes = tCommonSyndromeTypes == null ? null : tCommonSyndromeTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.symptom_origin
     *
     * @return the value of miss_symptom.symptom_origin
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getSymptomOrigin() {
        return symptomOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.symptom_origin
     *
     * @param symptomOrigin the value for miss_symptom.symptom_origin
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setSymptomOrigin(String symptomOrigin) {
        this.symptomOrigin = symptomOrigin == null ? null : symptomOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.task_json
     *
     * @return the value of miss_symptom.task_json
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getTaskJson() {
        return taskJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.task_json
     *
     * @param taskJson the value for miss_symptom.task_json
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setTaskJson(String taskJson) {
        this.taskJson = taskJson == null ? null : taskJson.trim();
    }
}