package com.med.info.domain;

public class Miss_doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.name
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.sex
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.origin
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.nation
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.birthday
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.dieday
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String dieday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.graduate
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String graduate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.profession
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.experts_time
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String expertsTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.birthplace_district_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private Long birthplaceDistrictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.task_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.task_status
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String taskStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.id
     *
     * @return the value of miss_doctor.id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.id
     *
     * @param id the value for miss_doctor.id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.name
     *
     * @return the value of miss_doctor.name
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.name
     *
     * @param name the value for miss_doctor.name
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.sex
     *
     * @return the value of miss_doctor.sex
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.sex
     *
     * @param sex the value for miss_doctor.sex
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.origin
     *
     * @return the value of miss_doctor.origin
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.origin
     *
     * @param origin the value for miss_doctor.origin
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.nation
     *
     * @return the value of miss_doctor.nation
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.nation
     *
     * @param nation the value for miss_doctor.nation
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.birthday
     *
     * @return the value of miss_doctor.birthday
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.birthday
     *
     * @param birthday the value for miss_doctor.birthday
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.dieday
     *
     * @return the value of miss_doctor.dieday
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getDieday() {
        return dieday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.dieday
     *
     * @param dieday the value for miss_doctor.dieday
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setDieday(String dieday) {
        this.dieday = dieday == null ? null : dieday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.graduate
     *
     * @return the value of miss_doctor.graduate
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getGraduate() {
        return graduate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.graduate
     *
     * @param graduate the value for miss_doctor.graduate
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setGraduate(String graduate) {
        this.graduate = graduate == null ? null : graduate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.profession
     *
     * @return the value of miss_doctor.profession
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.profession
     *
     * @param profession the value for miss_doctor.profession
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.experts_time
     *
     * @return the value of miss_doctor.experts_time
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getExpertsTime() {
        return expertsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.experts_time
     *
     * @param expertsTime the value for miss_doctor.experts_time
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setExpertsTime(String expertsTime) {
        this.expertsTime = expertsTime == null ? null : expertsTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.birthplace_district_id
     *
     * @return the value of miss_doctor.birthplace_district_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public Long getBirthplaceDistrictId() {
        return birthplaceDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.birthplace_district_id
     *
     * @param birthplaceDistrictId the value for miss_doctor.birthplace_district_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setBirthplaceDistrictId(Long birthplaceDistrictId) {
        this.birthplaceDistrictId = birthplaceDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.task_id
     *
     * @return the value of miss_doctor.task_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.task_id
     *
     * @param taskId the value for miss_doctor.task_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.task_status
     *
     * @return the value of miss_doctor.task_status
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.task_status
     *
     * @param taskStatus the value for miss_doctor.task_status
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }
}