package com.med.info.domain;

public class Miss_symptom extends BaseDomain{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.chinese_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String chineseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.english_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.other_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String otherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.symptom
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String symptom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.treatment
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String treatment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.clinical_manifestation
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String clinicalManifestation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.department_id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private Long departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.main_causes
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String mainCauses;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.common_symptom
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String commonSymptom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.multiple_population
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String multiplePopulation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.infectivity
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private Integer infectivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.inspection_items
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String inspectionItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.reserve1
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.reserve2
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.reserve3
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String reserve3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.dataStatus
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String datastatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.task_id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.task_status
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String taskStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.id
     *
     * @return the value of miss_symptom.id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.id
     *
     * @param id the value for miss_symptom.id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.chinese_name
     *
     * @return the value of miss_symptom.chinese_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getChineseName() {
        return chineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.chinese_name
     *
     * @param chineseName the value for miss_symptom.chinese_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName == null ? null : chineseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.english_name
     *
     * @return the value of miss_symptom.english_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.english_name
     *
     * @param englishName the value for miss_symptom.english_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.other_name
     *
     * @return the value of miss_symptom.other_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getOtherName() {
        return otherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.other_name
     *
     * @param otherName the value for miss_symptom.other_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setOtherName(String otherName) {
        this.otherName = otherName == null ? null : otherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.symptom
     *
     * @return the value of miss_symptom.symptom
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.symptom
     *
     * @param symptom the value for miss_symptom.symptom
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.treatment
     *
     * @return the value of miss_symptom.treatment
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getTreatment() {
        return treatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.treatment
     *
     * @param treatment the value for miss_symptom.treatment
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setTreatment(String treatment) {
        this.treatment = treatment == null ? null : treatment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.clinical_manifestation
     *
     * @return the value of miss_symptom.clinical_manifestation
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getClinicalManifestation() {
        return clinicalManifestation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.clinical_manifestation
     *
     * @param clinicalManifestation the value for miss_symptom.clinical_manifestation
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setClinicalManifestation(String clinicalManifestation) {
        this.clinicalManifestation = clinicalManifestation == null ? null : clinicalManifestation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.department_id
     *
     * @return the value of miss_symptom.department_id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.department_id
     *
     * @param departmentId the value for miss_symptom.department_id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.main_causes
     *
     * @return the value of miss_symptom.main_causes
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getMainCauses() {
        return mainCauses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.main_causes
     *
     * @param mainCauses the value for miss_symptom.main_causes
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setMainCauses(String mainCauses) {
        this.mainCauses = mainCauses == null ? null : mainCauses.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.common_symptom
     *
     * @return the value of miss_symptom.common_symptom
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getCommonSymptom() {
        return commonSymptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.common_symptom
     *
     * @param commonSymptom the value for miss_symptom.common_symptom
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setCommonSymptom(String commonSymptom) {
        this.commonSymptom = commonSymptom == null ? null : commonSymptom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.multiple_population
     *
     * @return the value of miss_symptom.multiple_population
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getMultiplePopulation() {
        return multiplePopulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.multiple_population
     *
     * @param multiplePopulation the value for miss_symptom.multiple_population
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setMultiplePopulation(String multiplePopulation) {
        this.multiplePopulation = multiplePopulation == null ? null : multiplePopulation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.infectivity
     *
     * @return the value of miss_symptom.infectivity
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public Integer getInfectivity() {
        return infectivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.infectivity
     *
     * @param infectivity the value for miss_symptom.infectivity
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setInfectivity(Integer infectivity) {
        this.infectivity = infectivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.inspection_items
     *
     * @return the value of miss_symptom.inspection_items
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getInspectionItems() {
        return inspectionItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.inspection_items
     *
     * @param inspectionItems the value for miss_symptom.inspection_items
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setInspectionItems(String inspectionItems) {
        this.inspectionItems = inspectionItems == null ? null : inspectionItems.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.reserve1
     *
     * @return the value of miss_symptom.reserve1
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.reserve1
     *
     * @param reserve1 the value for miss_symptom.reserve1
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.reserve2
     *
     * @return the value of miss_symptom.reserve2
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.reserve2
     *
     * @param reserve2 the value for miss_symptom.reserve2
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.reserve3
     *
     * @return the value of miss_symptom.reserve3
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.reserve3
     *
     * @param reserve3 the value for miss_symptom.reserve3
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.dataStatus
     *
     * @return the value of miss_symptom.dataStatus
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getDatastatus() {
        return datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.dataStatus
     *
     * @param datastatus the value for miss_symptom.dataStatus
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setDatastatus(String datastatus) {
        this.datastatus = datastatus == null ? null : datastatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.task_id
     *
     * @return the value of miss_symptom.task_id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.task_id
     *
     * @param taskId the value for miss_symptom.task_id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.task_status
     *
     * @return the value of miss_symptom.task_status
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.task_status
     *
     * @param taskStatus the value for miss_symptom.task_status
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }
}