package com.med.info.domain;

public class Miss_institution_doctor_mapping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution_doctor_mapping.id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution_doctor_mapping.institution_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private Long institutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution_doctor_mapping.doctor_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private Long doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution_doctor_mapping.weight
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution_doctor_mapping.task_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution_doctor_mapping.task_status
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_institution_doctor_mapping.task_json
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String taskJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution_doctor_mapping.id
     *
     * @return the value of miss_institution_doctor_mapping.id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution_doctor_mapping.id
     *
     * @param id the value for miss_institution_doctor_mapping.id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution_doctor_mapping.institution_id
     *
     * @return the value of miss_institution_doctor_mapping.institution_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public Long getInstitutionId() {
        return institutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution_doctor_mapping.institution_id
     *
     * @param institutionId the value for miss_institution_doctor_mapping.institution_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setInstitutionId(Long institutionId) {
        this.institutionId = institutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution_doctor_mapping.doctor_id
     *
     * @return the value of miss_institution_doctor_mapping.doctor_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution_doctor_mapping.doctor_id
     *
     * @param doctorId the value for miss_institution_doctor_mapping.doctor_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution_doctor_mapping.weight
     *
     * @return the value of miss_institution_doctor_mapping.weight
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution_doctor_mapping.weight
     *
     * @param weight the value for miss_institution_doctor_mapping.weight
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution_doctor_mapping.task_id
     *
     * @return the value of miss_institution_doctor_mapping.task_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution_doctor_mapping.task_id
     *
     * @param taskId the value for miss_institution_doctor_mapping.task_id
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution_doctor_mapping.task_status
     *
     * @return the value of miss_institution_doctor_mapping.task_status
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution_doctor_mapping.task_status
     *
     * @param taskStatus the value for miss_institution_doctor_mapping.task_status
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_institution_doctor_mapping.task_json
     *
     * @return the value of miss_institution_doctor_mapping.task_json
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getTaskJson() {
        return taskJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_institution_doctor_mapping.task_json
     *
     * @param taskJson the value for miss_institution_doctor_mapping.task_json
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setTaskJson(String taskJson) {
        this.taskJson = taskJson == null ? null : taskJson.trim();
    }
}