package com.med.info.domain;

public class Miss_disease_department_mapping extends BaseDomain {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_disease_department_mapping.disease_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Long diseaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_disease_department_mapping.department_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Long departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_disease_department_mapping.disease_id
     *
     * @return the value of miss_disease_department_mapping.disease_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Long getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_disease_department_mapping.disease_id
     *
     * @param diseaseId the value for miss_disease_department_mapping.disease_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDiseaseId(Long diseaseId) {
        this.diseaseId = diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_disease_department_mapping.department_id
     *
     * @return the value of miss_disease_department_mapping.department_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_disease_department_mapping.department_id
     *
     * @param departmentId the value for miss_disease_department_mapping.department_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }
}