package com.med.info.domain;

import java.util.Date;

public class Miss_control_approval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.id
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.taskId
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private String taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.referModel
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private String refermodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.referModelChineseName
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private String refermodelchinesename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.fisrtTrailApprovalResult
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private String fisrttrailapprovalresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.secondTrailApprovalResult
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private String secondtrailapprovalresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.finalTrailApprovalResult
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private String finaltrailapprovalresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.firstApprovalPoint
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private Integer firstapprovalpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.secondApprovalPoint
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private Integer secondapprovalpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.finalApprovalPoint
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private Integer finalapprovalpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.firstTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private Date firsttrailsuggesttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.secondTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private Date secondtrailsuggesttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.finalTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    private Date finaltrailsuggesttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.id
     *
     * @return the value of miss_control_approval.id
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.id
     *
     * @param id the value for miss_control_approval.id
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.taskId
     *
     * @return the value of miss_control_approval.taskId
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.taskId
     *
     * @param taskid the value for miss_control_approval.taskId
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.referModel
     *
     * @return the value of miss_control_approval.referModel
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public String getRefermodel() {
        return refermodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.referModel
     *
     * @param refermodel the value for miss_control_approval.referModel
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setRefermodel(String refermodel) {
        this.refermodel = refermodel == null ? null : refermodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.referModelChineseName
     *
     * @return the value of miss_control_approval.referModelChineseName
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public String getRefermodelchinesename() {
        return refermodelchinesename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.referModelChineseName
     *
     * @param refermodelchinesename the value for miss_control_approval.referModelChineseName
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setRefermodelchinesename(String refermodelchinesename) {
        this.refermodelchinesename = refermodelchinesename == null ? null : refermodelchinesename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.fisrtTrailApprovalResult
     *
     * @return the value of miss_control_approval.fisrtTrailApprovalResult
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public String getFisrttrailapprovalresult() {
        return fisrttrailapprovalresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.fisrtTrailApprovalResult
     *
     * @param fisrttrailapprovalresult the value for miss_control_approval.fisrtTrailApprovalResult
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setFisrttrailapprovalresult(String fisrttrailapprovalresult) {
        this.fisrttrailapprovalresult = fisrttrailapprovalresult == null ? null : fisrttrailapprovalresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.secondTrailApprovalResult
     *
     * @return the value of miss_control_approval.secondTrailApprovalResult
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public String getSecondtrailapprovalresult() {
        return secondtrailapprovalresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.secondTrailApprovalResult
     *
     * @param secondtrailapprovalresult the value for miss_control_approval.secondTrailApprovalResult
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setSecondtrailapprovalresult(String secondtrailapprovalresult) {
        this.secondtrailapprovalresult = secondtrailapprovalresult == null ? null : secondtrailapprovalresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.finalTrailApprovalResult
     *
     * @return the value of miss_control_approval.finalTrailApprovalResult
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public String getFinaltrailapprovalresult() {
        return finaltrailapprovalresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.finalTrailApprovalResult
     *
     * @param finaltrailapprovalresult the value for miss_control_approval.finalTrailApprovalResult
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setFinaltrailapprovalresult(String finaltrailapprovalresult) {
        this.finaltrailapprovalresult = finaltrailapprovalresult == null ? null : finaltrailapprovalresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.firstApprovalPoint
     *
     * @return the value of miss_control_approval.firstApprovalPoint
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public Integer getFirstapprovalpoint() {
        return firstapprovalpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.firstApprovalPoint
     *
     * @param firstapprovalpoint the value for miss_control_approval.firstApprovalPoint
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setFirstapprovalpoint(Integer firstapprovalpoint) {
        this.firstapprovalpoint = firstapprovalpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.secondApprovalPoint
     *
     * @return the value of miss_control_approval.secondApprovalPoint
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public Integer getSecondapprovalpoint() {
        return secondapprovalpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.secondApprovalPoint
     *
     * @param secondapprovalpoint the value for miss_control_approval.secondApprovalPoint
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setSecondapprovalpoint(Integer secondapprovalpoint) {
        this.secondapprovalpoint = secondapprovalpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.finalApprovalPoint
     *
     * @return the value of miss_control_approval.finalApprovalPoint
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public Integer getFinalapprovalpoint() {
        return finalapprovalpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.finalApprovalPoint
     *
     * @param finalapprovalpoint the value for miss_control_approval.finalApprovalPoint
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setFinalapprovalpoint(Integer finalapprovalpoint) {
        this.finalapprovalpoint = finalapprovalpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.firstTrailSuggestTime
     *
     * @return the value of miss_control_approval.firstTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public Date getFirsttrailsuggesttime() {
        return firsttrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.firstTrailSuggestTime
     *
     * @param firsttrailsuggesttime the value for miss_control_approval.firstTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setFirsttrailsuggesttime(Date firsttrailsuggesttime) {
        this.firsttrailsuggesttime = firsttrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.secondTrailSuggestTime
     *
     * @return the value of miss_control_approval.secondTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public Date getSecondtrailsuggesttime() {
        return secondtrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.secondTrailSuggestTime
     *
     * @param secondtrailsuggesttime the value for miss_control_approval.secondTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setSecondtrailsuggesttime(Date secondtrailsuggesttime) {
        this.secondtrailsuggesttime = secondtrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.finalTrailSuggestTime
     *
     * @return the value of miss_control_approval.finalTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public Date getFinaltrailsuggesttime() {
        return finaltrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.finalTrailSuggestTime
     *
     * @param finaltrailsuggesttime the value for miss_control_approval.finalTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 20:00:12 CST 2019
     */
    public void setFinaltrailsuggesttime(Date finaltrailsuggesttime) {
        this.finaltrailsuggesttime = finaltrailsuggesttime;
    }
}