package com.med.info.domain;

public class Miss_control_group extends BaseDomain{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_group.groupUuid
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String groupuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_group.groupCode
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String groupcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_group.groupName
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_group.groupStatus
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String groupstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_group.groupCreateDate
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String groupcreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_group.groupCreateTime
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String groupcreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_group.groupUuid
     *
     * @return the value of miss_control_group.groupUuid
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getGroupuuid() {
        return groupuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_group.groupUuid
     *
     * @param groupuuid the value for miss_control_group.groupUuid
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setGroupuuid(String groupuuid) {
        this.groupuuid = groupuuid == null ? null : groupuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_group.groupCode
     *
     * @return the value of miss_control_group.groupCode
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getGroupcode() {
        return groupcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_group.groupCode
     *
     * @param groupcode the value for miss_control_group.groupCode
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setGroupcode(String groupcode) {
        this.groupcode = groupcode == null ? null : groupcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_group.groupName
     *
     * @return the value of miss_control_group.groupName
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_group.groupName
     *
     * @param groupname the value for miss_control_group.groupName
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_group.groupStatus
     *
     * @return the value of miss_control_group.groupStatus
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getGroupstatus() {
        return groupstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_group.groupStatus
     *
     * @param groupstatus the value for miss_control_group.groupStatus
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setGroupstatus(String groupstatus) {
        this.groupstatus = groupstatus == null ? null : groupstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_group.groupCreateDate
     *
     * @return the value of miss_control_group.groupCreateDate
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getGroupcreatedate() {
        return groupcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_group.groupCreateDate
     *
     * @param groupcreatedate the value for miss_control_group.groupCreateDate
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setGroupcreatedate(String groupcreatedate) {
        this.groupcreatedate = groupcreatedate == null ? null : groupcreatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_group.groupCreateTime
     *
     * @return the value of miss_control_group.groupCreateTime
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getGroupcreatetime() {
        return groupcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_group.groupCreateTime
     *
     * @param groupcreatetime the value for miss_control_group.groupCreateTime
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setGroupcreatetime(String groupcreatetime) {
        this.groupcreatetime = groupcreatetime == null ? null : groupcreatetime.trim();
    }
}