package com.med.info.domain;

public class Miss_doctorWithBLOBs extends Miss_doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.intro
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.picturepath
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String picturepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.honorary
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String honorary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.clinic_professional
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String clinicProfessional;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.edu_professional
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String eduProfessional;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.education
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.work_experience
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String workExperience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.treat_area
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String treatArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.research_area
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String researchArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.academic
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String academic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.production
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String production;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.awards
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String awards;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.science
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String science;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.socialization
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String socialization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.thesis
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String thesis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.bookmaking
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String bookmaking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.heritage_map
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String heritageMap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.reference_material
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String referenceMaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_doctor.task_json
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String taskJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.intro
     *
     * @return the value of miss_doctor.intro
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.intro
     *
     * @param intro the value for miss_doctor.intro
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.picturepath
     *
     * @return the value of miss_doctor.picturepath
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getPicturepath() {
        return picturepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.picturepath
     *
     * @param picturepath the value for miss_doctor.picturepath
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setPicturepath(String picturepath) {
        this.picturepath = picturepath == null ? null : picturepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.honorary
     *
     * @return the value of miss_doctor.honorary
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getHonorary() {
        return honorary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.honorary
     *
     * @param honorary the value for miss_doctor.honorary
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setHonorary(String honorary) {
        this.honorary = honorary == null ? null : honorary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.clinic_professional
     *
     * @return the value of miss_doctor.clinic_professional
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getClinicProfessional() {
        return clinicProfessional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.clinic_professional
     *
     * @param clinicProfessional the value for miss_doctor.clinic_professional
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setClinicProfessional(String clinicProfessional) {
        this.clinicProfessional = clinicProfessional == null ? null : clinicProfessional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.edu_professional
     *
     * @return the value of miss_doctor.edu_professional
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getEduProfessional() {
        return eduProfessional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.edu_professional
     *
     * @param eduProfessional the value for miss_doctor.edu_professional
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setEduProfessional(String eduProfessional) {
        this.eduProfessional = eduProfessional == null ? null : eduProfessional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.education
     *
     * @return the value of miss_doctor.education
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.education
     *
     * @param education the value for miss_doctor.education
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.work_experience
     *
     * @return the value of miss_doctor.work_experience
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getWorkExperience() {
        return workExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.work_experience
     *
     * @param workExperience the value for miss_doctor.work_experience
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setWorkExperience(String workExperience) {
        this.workExperience = workExperience == null ? null : workExperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.treat_area
     *
     * @return the value of miss_doctor.treat_area
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getTreatArea() {
        return treatArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.treat_area
     *
     * @param treatArea the value for miss_doctor.treat_area
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setTreatArea(String treatArea) {
        this.treatArea = treatArea == null ? null : treatArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.research_area
     *
     * @return the value of miss_doctor.research_area
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getResearchArea() {
        return researchArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.research_area
     *
     * @param researchArea the value for miss_doctor.research_area
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setResearchArea(String researchArea) {
        this.researchArea = researchArea == null ? null : researchArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.academic
     *
     * @return the value of miss_doctor.academic
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getAcademic() {
        return academic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.academic
     *
     * @param academic the value for miss_doctor.academic
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setAcademic(String academic) {
        this.academic = academic == null ? null : academic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.production
     *
     * @return the value of miss_doctor.production
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getProduction() {
        return production;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.production
     *
     * @param production the value for miss_doctor.production
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setProduction(String production) {
        this.production = production == null ? null : production.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.awards
     *
     * @return the value of miss_doctor.awards
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getAwards() {
        return awards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.awards
     *
     * @param awards the value for miss_doctor.awards
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setAwards(String awards) {
        this.awards = awards == null ? null : awards.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.science
     *
     * @return the value of miss_doctor.science
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getScience() {
        return science;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.science
     *
     * @param science the value for miss_doctor.science
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setScience(String science) {
        this.science = science == null ? null : science.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.socialization
     *
     * @return the value of miss_doctor.socialization
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getSocialization() {
        return socialization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.socialization
     *
     * @param socialization the value for miss_doctor.socialization
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setSocialization(String socialization) {
        this.socialization = socialization == null ? null : socialization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.thesis
     *
     * @return the value of miss_doctor.thesis
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getThesis() {
        return thesis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.thesis
     *
     * @param thesis the value for miss_doctor.thesis
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setThesis(String thesis) {
        this.thesis = thesis == null ? null : thesis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.bookmaking
     *
     * @return the value of miss_doctor.bookmaking
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getBookmaking() {
        return bookmaking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.bookmaking
     *
     * @param bookmaking the value for miss_doctor.bookmaking
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setBookmaking(String bookmaking) {
        this.bookmaking = bookmaking == null ? null : bookmaking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.heritage_map
     *
     * @return the value of miss_doctor.heritage_map
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getHeritageMap() {
        return heritageMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.heritage_map
     *
     * @param heritageMap the value for miss_doctor.heritage_map
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setHeritageMap(String heritageMap) {
        this.heritageMap = heritageMap == null ? null : heritageMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.reference_material
     *
     * @return the value of miss_doctor.reference_material
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getReferenceMaterial() {
        return referenceMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.reference_material
     *
     * @param referenceMaterial the value for miss_doctor.reference_material
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setReferenceMaterial(String referenceMaterial) {
        this.referenceMaterial = referenceMaterial == null ? null : referenceMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_doctor.task_json
     *
     * @return the value of miss_doctor.task_json
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getTaskJson() {
        return taskJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_doctor.task_json
     *
     * @param taskJson the value for miss_doctor.task_json
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setTaskJson(String taskJson) {
        this.taskJson = taskJson == null ? null : taskJson.trim();
    }
}