package com.med.info.domain;

public class Miss_control_userAndGroup extends BaseDomain{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_userAndGroup.UGuuid
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String uguuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_userAndGroup.userCode
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String usercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_userAndGroup.groupCode
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String groupcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_userAndGroup.relationStatus
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String relationstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_userAndGroup.relationCreateDate
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String relationcreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_userAndGroup.relationCreateTime
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    private String relationcreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_userAndGroup.UGuuid
     *
     * @return the value of miss_control_userAndGroup.UGuuid
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getUguuid() {
        return uguuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_userAndGroup.UGuuid
     *
     * @param uguuid the value for miss_control_userAndGroup.UGuuid
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setUguuid(String uguuid) {
        this.uguuid = uguuid == null ? null : uguuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_userAndGroup.userCode
     *
     * @return the value of miss_control_userAndGroup.userCode
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_userAndGroup.userCode
     *
     * @param usercode the value for miss_control_userAndGroup.userCode
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_userAndGroup.groupCode
     *
     * @return the value of miss_control_userAndGroup.groupCode
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getGroupcode() {
        return groupcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_userAndGroup.groupCode
     *
     * @param groupcode the value for miss_control_userAndGroup.groupCode
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setGroupcode(String groupcode) {
        this.groupcode = groupcode == null ? null : groupcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_userAndGroup.relationStatus
     *
     * @return the value of miss_control_userAndGroup.relationStatus
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getRelationstatus() {
        return relationstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_userAndGroup.relationStatus
     *
     * @param relationstatus the value for miss_control_userAndGroup.relationStatus
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setRelationstatus(String relationstatus) {
        this.relationstatus = relationstatus == null ? null : relationstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_userAndGroup.relationCreateDate
     *
     * @return the value of miss_control_userAndGroup.relationCreateDate
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getRelationcreatedate() {
        return relationcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_userAndGroup.relationCreateDate
     *
     * @param relationcreatedate the value for miss_control_userAndGroup.relationCreateDate
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setRelationcreatedate(String relationcreatedate) {
        this.relationcreatedate = relationcreatedate == null ? null : relationcreatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_userAndGroup.relationCreateTime
     *
     * @return the value of miss_control_userAndGroup.relationCreateTime
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public String getRelationcreatetime() {
        return relationcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_userAndGroup.relationCreateTime
     *
     * @param relationcreatetime the value for miss_control_userAndGroup.relationCreateTime
     *
     * @mbg.generated Sun May 12 13:17:25 CST 2019
     */
    public void setRelationcreatetime(String relationcreatetime) {
        this.relationcreatetime = relationcreatetime == null ? null : relationcreatetime.trim();
    }
}