package com.med.info.domain;

public class Miss_medical extends BaseDomain{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.medical_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private Integer medicalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.com_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String comName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.chinese_pinyin
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String chinesePinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.alisa_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String alisaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.shop_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.english_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.drug_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String drugType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.ytime
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String ytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.enterprise
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String enterprise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.approval_num
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String approvalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.health_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String healthType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.storage_method
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String storageMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.drug_identifying
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String drugIdentifying;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.address
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.recipe_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String recipeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.price
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.picture_path
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String picturePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.dataStatus
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String datastatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.task_id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.task_status
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    private String taskStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.id
     *
     * @return the value of miss_medical.id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.id
     *
     * @param id the value for miss_medical.id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.medical_type
     *
     * @return the value of miss_medical.medical_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public Integer getMedicalType() {
        return medicalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.medical_type
     *
     * @param medicalType the value for miss_medical.medical_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setMedicalType(Integer medicalType) {
        this.medicalType = medicalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.com_name
     *
     * @return the value of miss_medical.com_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.com_name
     *
     * @param comName the value for miss_medical.com_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.chinese_pinyin
     *
     * @return the value of miss_medical.chinese_pinyin
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getChinesePinyin() {
        return chinesePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.chinese_pinyin
     *
     * @param chinesePinyin the value for miss_medical.chinese_pinyin
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setChinesePinyin(String chinesePinyin) {
        this.chinesePinyin = chinesePinyin == null ? null : chinesePinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.alisa_name
     *
     * @return the value of miss_medical.alisa_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getAlisaName() {
        return alisaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.alisa_name
     *
     * @param alisaName the value for miss_medical.alisa_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setAlisaName(String alisaName) {
        this.alisaName = alisaName == null ? null : alisaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.shop_name
     *
     * @return the value of miss_medical.shop_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.shop_name
     *
     * @param shopName the value for miss_medical.shop_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.english_name
     *
     * @return the value of miss_medical.english_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.english_name
     *
     * @param englishName the value for miss_medical.english_name
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.drug_type
     *
     * @return the value of miss_medical.drug_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getDrugType() {
        return drugType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.drug_type
     *
     * @param drugType the value for miss_medical.drug_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setDrugType(String drugType) {
        this.drugType = drugType == null ? null : drugType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.ytime
     *
     * @return the value of miss_medical.ytime
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getYtime() {
        return ytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.ytime
     *
     * @param ytime the value for miss_medical.ytime
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setYtime(String ytime) {
        this.ytime = ytime == null ? null : ytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.enterprise
     *
     * @return the value of miss_medical.enterprise
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getEnterprise() {
        return enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.enterprise
     *
     * @param enterprise the value for miss_medical.enterprise
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setEnterprise(String enterprise) {
        this.enterprise = enterprise == null ? null : enterprise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.approval_num
     *
     * @return the value of miss_medical.approval_num
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getApprovalNum() {
        return approvalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.approval_num
     *
     * @param approvalNum the value for miss_medical.approval_num
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setApprovalNum(String approvalNum) {
        this.approvalNum = approvalNum == null ? null : approvalNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.health_type
     *
     * @return the value of miss_medical.health_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getHealthType() {
        return healthType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.health_type
     *
     * @param healthType the value for miss_medical.health_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setHealthType(String healthType) {
        this.healthType = healthType == null ? null : healthType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.storage_method
     *
     * @return the value of miss_medical.storage_method
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getStorageMethod() {
        return storageMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.storage_method
     *
     * @param storageMethod the value for miss_medical.storage_method
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setStorageMethod(String storageMethod) {
        this.storageMethod = storageMethod == null ? null : storageMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.drug_identifying
     *
     * @return the value of miss_medical.drug_identifying
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getDrugIdentifying() {
        return drugIdentifying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.drug_identifying
     *
     * @param drugIdentifying the value for miss_medical.drug_identifying
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setDrugIdentifying(String drugIdentifying) {
        this.drugIdentifying = drugIdentifying == null ? null : drugIdentifying.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.address
     *
     * @return the value of miss_medical.address
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.address
     *
     * @param address the value for miss_medical.address
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.recipe_type
     *
     * @return the value of miss_medical.recipe_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getRecipeType() {
        return recipeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.recipe_type
     *
     * @param recipeType the value for miss_medical.recipe_type
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setRecipeType(String recipeType) {
        this.recipeType = recipeType == null ? null : recipeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.price
     *
     * @return the value of miss_medical.price
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.price
     *
     * @param price the value for miss_medical.price
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.picture_path
     *
     * @return the value of miss_medical.picture_path
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.picture_path
     *
     * @param picturePath the value for miss_medical.picture_path
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath == null ? null : picturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.dataStatus
     *
     * @return the value of miss_medical.dataStatus
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getDatastatus() {
        return datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.dataStatus
     *
     * @param datastatus the value for miss_medical.dataStatus
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setDatastatus(String datastatus) {
        this.datastatus = datastatus == null ? null : datastatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.task_id
     *
     * @return the value of miss_medical.task_id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.task_id
     *
     * @param taskId the value for miss_medical.task_id
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.task_status
     *
     * @return the value of miss_medical.task_status
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.task_status
     *
     * @param taskStatus the value for miss_medical.task_status
     *
     * @mbg.generated Mon Nov 26 11:32:45 CST 2018
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }
}