package com.med.info.domain;

public class Miss_western_disease extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_western_disease.disease_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private Long diseaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_western_disease.reserve1
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_western_disease.reserve2
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_western_disease.reserve3
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String reserve3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_western_disease.disease_id
     *
     * @return the value of miss_western_disease.disease_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public Long getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_western_disease.disease_id
     *
     * @param diseaseId the value for miss_western_disease.disease_id
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setDiseaseId(Long diseaseId) {
        this.diseaseId = diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_western_disease.reserve1
     *
     * @return the value of miss_western_disease.reserve1
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_western_disease.reserve1
     *
     * @param reserve1 the value for miss_western_disease.reserve1
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_western_disease.reserve2
     *
     * @return the value of miss_western_disease.reserve2
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_western_disease.reserve2
     *
     * @param reserve2 the value for miss_western_disease.reserve2
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_western_disease.reserve3
     *
     * @return the value of miss_western_disease.reserve3
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_western_disease.reserve3
     *
     * @param reserve3 the value for miss_western_disease.reserve3
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }
}