package com.med.info.domain;

public class Miss_medicalWithBLOBs extends Miss_medical {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.constitute
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String constitute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.property
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.func
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String func;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.mainAttend
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String mainattend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.standard
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String standard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.pharmacology
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String pharmacology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.toxicologicalEffects
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String toxicologicaleffects;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.clinicalApplication
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String clinicalapplication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.adverseReactions
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String adversereactions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.taboo
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String taboo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.notice
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String notice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.identify
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String identify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.pharmacyCheck
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String pharmacycheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.contentPic
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String contentpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.medicFormat
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String medicformat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.notes
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.component
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.mainMeffect
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String mainmeffect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.analyze
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String analyze;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.interactions
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String interactions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.history
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String history;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.drugIntroduce
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String drugintroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.awards
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String awards;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.research
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String research;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.monograph
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String monograph;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.messageFrom
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String messagefrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.product_info
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String productInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical.task_json
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    private String taskJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.constitute
     *
     * @return the value of miss_medical.constitute
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getConstitute() {
        return constitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.constitute
     *
     * @param constitute the value for miss_medical.constitute
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setConstitute(String constitute) {
        this.constitute = constitute == null ? null : constitute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.property
     *
     * @return the value of miss_medical.property
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.property
     *
     * @param property the value for miss_medical.property
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.func
     *
     * @return the value of miss_medical.func
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getFunc() {
        return func;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.func
     *
     * @param func the value for miss_medical.func
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setFunc(String func) {
        this.func = func == null ? null : func.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.mainAttend
     *
     * @return the value of miss_medical.mainAttend
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getMainattend() {
        return mainattend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.mainAttend
     *
     * @param mainattend the value for miss_medical.mainAttend
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setMainattend(String mainattend) {
        this.mainattend = mainattend == null ? null : mainattend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.standard
     *
     * @return the value of miss_medical.standard
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.standard
     *
     * @param standard the value for miss_medical.standard
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.pharmacology
     *
     * @return the value of miss_medical.pharmacology
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getPharmacology() {
        return pharmacology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.pharmacology
     *
     * @param pharmacology the value for miss_medical.pharmacology
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setPharmacology(String pharmacology) {
        this.pharmacology = pharmacology == null ? null : pharmacology.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.toxicologicalEffects
     *
     * @return the value of miss_medical.toxicologicalEffects
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getToxicologicaleffects() {
        return toxicologicaleffects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.toxicologicalEffects
     *
     * @param toxicologicaleffects the value for miss_medical.toxicologicalEffects
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setToxicologicaleffects(String toxicologicaleffects) {
        this.toxicologicaleffects = toxicologicaleffects == null ? null : toxicologicaleffects.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.clinicalApplication
     *
     * @return the value of miss_medical.clinicalApplication
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getClinicalapplication() {
        return clinicalapplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.clinicalApplication
     *
     * @param clinicalapplication the value for miss_medical.clinicalApplication
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setClinicalapplication(String clinicalapplication) {
        this.clinicalapplication = clinicalapplication == null ? null : clinicalapplication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.adverseReactions
     *
     * @return the value of miss_medical.adverseReactions
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getAdversereactions() {
        return adversereactions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.adverseReactions
     *
     * @param adversereactions the value for miss_medical.adverseReactions
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setAdversereactions(String adversereactions) {
        this.adversereactions = adversereactions == null ? null : adversereactions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.taboo
     *
     * @return the value of miss_medical.taboo
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getTaboo() {
        return taboo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.taboo
     *
     * @param taboo the value for miss_medical.taboo
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setTaboo(String taboo) {
        this.taboo = taboo == null ? null : taboo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.notice
     *
     * @return the value of miss_medical.notice
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.notice
     *
     * @param notice the value for miss_medical.notice
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.identify
     *
     * @return the value of miss_medical.identify
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.identify
     *
     * @param identify the value for miss_medical.identify
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setIdentify(String identify) {
        this.identify = identify == null ? null : identify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.pharmacyCheck
     *
     * @return the value of miss_medical.pharmacyCheck
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getPharmacycheck() {
        return pharmacycheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.pharmacyCheck
     *
     * @param pharmacycheck the value for miss_medical.pharmacyCheck
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setPharmacycheck(String pharmacycheck) {
        this.pharmacycheck = pharmacycheck == null ? null : pharmacycheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.contentPic
     *
     * @return the value of miss_medical.contentPic
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getContentpic() {
        return contentpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.contentPic
     *
     * @param contentpic the value for miss_medical.contentPic
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setContentpic(String contentpic) {
        this.contentpic = contentpic == null ? null : contentpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.medicFormat
     *
     * @return the value of miss_medical.medicFormat
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getMedicformat() {
        return medicformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.medicFormat
     *
     * @param medicformat the value for miss_medical.medicFormat
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setMedicformat(String medicformat) {
        this.medicformat = medicformat == null ? null : medicformat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.notes
     *
     * @return the value of miss_medical.notes
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.notes
     *
     * @param notes the value for miss_medical.notes
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.component
     *
     * @return the value of miss_medical.component
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.component
     *
     * @param component the value for miss_medical.component
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.mainMeffect
     *
     * @return the value of miss_medical.mainMeffect
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getMainmeffect() {
        return mainmeffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.mainMeffect
     *
     * @param mainmeffect the value for miss_medical.mainMeffect
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setMainmeffect(String mainmeffect) {
        this.mainmeffect = mainmeffect == null ? null : mainmeffect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.analyze
     *
     * @return the value of miss_medical.analyze
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getAnalyze() {
        return analyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.analyze
     *
     * @param analyze the value for miss_medical.analyze
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setAnalyze(String analyze) {
        this.analyze = analyze == null ? null : analyze.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.interactions
     *
     * @return the value of miss_medical.interactions
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getInteractions() {
        return interactions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.interactions
     *
     * @param interactions the value for miss_medical.interactions
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setInteractions(String interactions) {
        this.interactions = interactions == null ? null : interactions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.history
     *
     * @return the value of miss_medical.history
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getHistory() {
        return history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.history
     *
     * @param history the value for miss_medical.history
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setHistory(String history) {
        this.history = history == null ? null : history.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.drugIntroduce
     *
     * @return the value of miss_medical.drugIntroduce
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getDrugintroduce() {
        return drugintroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.drugIntroduce
     *
     * @param drugintroduce the value for miss_medical.drugIntroduce
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setDrugintroduce(String drugintroduce) {
        this.drugintroduce = drugintroduce == null ? null : drugintroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.awards
     *
     * @return the value of miss_medical.awards
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getAwards() {
        return awards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.awards
     *
     * @param awards the value for miss_medical.awards
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setAwards(String awards) {
        this.awards = awards == null ? null : awards.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.research
     *
     * @return the value of miss_medical.research
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getResearch() {
        return research;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.research
     *
     * @param research the value for miss_medical.research
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setResearch(String research) {
        this.research = research == null ? null : research.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.monograph
     *
     * @return the value of miss_medical.monograph
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getMonograph() {
        return monograph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.monograph
     *
     * @param monograph the value for miss_medical.monograph
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setMonograph(String monograph) {
        this.monograph = monograph == null ? null : monograph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.messageFrom
     *
     * @return the value of miss_medical.messageFrom
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getMessagefrom() {
        return messagefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.messageFrom
     *
     * @param messagefrom the value for miss_medical.messageFrom
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setMessagefrom(String messagefrom) {
        this.messagefrom = messagefrom == null ? null : messagefrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.product_info
     *
     * @return the value of miss_medical.product_info
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getProductInfo() {
        return productInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.product_info
     *
     * @param productInfo the value for miss_medical.product_info
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setProductInfo(String productInfo) {
        this.productInfo = productInfo == null ? null : productInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical.task_json
     *
     * @return the value of miss_medical.task_json
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public String getTaskJson() {
        return taskJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical.task_json
     *
     * @param taskJson the value for miss_medical.task_json
     *
     * @mbg.generated Sat Nov 17 18:29:49 CST 2018
     */
    public void setTaskJson(String taskJson) {
        this.taskJson = taskJson == null ? null : taskJson.trim();
    }
}