package com.med.info.domain;

import java.util.Date;

public class Miss_control_approval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.id
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.taskId
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    private String taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.referModel
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    private String refermodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.referModelChineseName
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    private String refermodelchinesename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.approvalResult
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    private String approvalresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.approvalPoint
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    private Integer approvalpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.firstTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    private Date firsttrailsuggesttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.secondTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    private Date secondtrailsuggesttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.finalTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    private Date finaltrailsuggesttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_control_approval.suggestion
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    private String suggestion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.id
     *
     * @return the value of miss_control_approval.id
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.id
     *
     * @param id the value for miss_control_approval.id
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.taskId
     *
     * @return the value of miss_control_approval.taskId
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.taskId
     *
     * @param taskid the value for miss_control_approval.taskId
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.referModel
     *
     * @return the value of miss_control_approval.referModel
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public String getRefermodel() {
        return refermodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.referModel
     *
     * @param refermodel the value for miss_control_approval.referModel
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public void setRefermodel(String refermodel) {
        this.refermodel = refermodel == null ? null : refermodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.referModelChineseName
     *
     * @return the value of miss_control_approval.referModelChineseName
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public String getRefermodelchinesename() {
        return refermodelchinesename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.referModelChineseName
     *
     * @param refermodelchinesename the value for miss_control_approval.referModelChineseName
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public void setRefermodelchinesename(String refermodelchinesename) {
        this.refermodelchinesename = refermodelchinesename == null ? null : refermodelchinesename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.approvalResult
     *
     * @return the value of miss_control_approval.approvalResult
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public String getApprovalresult() {
        return approvalresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.approvalResult
     *
     * @param approvalresult the value for miss_control_approval.approvalResult
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public void setApprovalresult(String approvalresult) {
        this.approvalresult = approvalresult == null ? null : approvalresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.approvalPoint
     *
     * @return the value of miss_control_approval.approvalPoint
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public Integer getApprovalpoint() {
        return approvalpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.approvalPoint
     *
     * @param approvalpoint the value for miss_control_approval.approvalPoint
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public void setApprovalpoint(Integer approvalpoint) {
        this.approvalpoint = approvalpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.firstTrailSuggestTime
     *
     * @return the value of miss_control_approval.firstTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public Date getFirsttrailsuggesttime() {
        return firsttrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.firstTrailSuggestTime
     *
     * @param firsttrailsuggesttime the value for miss_control_approval.firstTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public void setFirsttrailsuggesttime(Date firsttrailsuggesttime) {
        this.firsttrailsuggesttime = firsttrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.secondTrailSuggestTime
     *
     * @return the value of miss_control_approval.secondTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public Date getSecondtrailsuggesttime() {
        return secondtrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.secondTrailSuggestTime
     *
     * @param secondtrailsuggesttime the value for miss_control_approval.secondTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public void setSecondtrailsuggesttime(Date secondtrailsuggesttime) {
        this.secondtrailsuggesttime = secondtrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.finalTrailSuggestTime
     *
     * @return the value of miss_control_approval.finalTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public Date getFinaltrailsuggesttime() {
        return finaltrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.finalTrailSuggestTime
     *
     * @param finaltrailsuggesttime the value for miss_control_approval.finalTrailSuggestTime
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public void setFinaltrailsuggesttime(Date finaltrailsuggesttime) {
        this.finaltrailsuggesttime = finaltrailsuggesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_control_approval.suggestion
     *
     * @return the value of miss_control_approval.suggestion
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public String getSuggestion() {
        return suggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_control_approval.suggestion
     *
     * @param suggestion the value for miss_control_approval.suggestion
     *
     * @mbg.generated Tue Jan 01 00:34:03 CST 2019
     */
    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion == null ? null : suggestion.trim();
    }
}