package com.med.info.domain;

public class Miss_symptomWithBLOBs extends Miss_symptom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.inspection_items
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String inspectionItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.t_other_therapies
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String tOtherTherapies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.common_diseases
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String commonDiseases;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.t_preventive_nursing
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String tPreventiveNursing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.syndrome
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String syndrome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.data_reference
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String dataReference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.chinese_medicine
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String chineseMedicine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.pathogeny
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String pathogeny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.pathogenesis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String pathogenesis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.dialectical_points
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String dialecticalPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.symptom_analysis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String symptomAnalysis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.common_chinese_medicine
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String commonChineseMedicine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.t_common_syndrome_types
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String tCommonSyndromeTypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.symptom_origin
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String symptomOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.task_json
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String taskJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.inspect
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String inspect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.diagnosi
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String diagnosi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.differential_diagnosis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String differentialDiagnosis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.clinical_significance
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String clinicalSignificance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.daily_nursing
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String dailyNursing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.attention_matter
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String attentionMatter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.influence_factor
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String influenceFactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.consultation
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String consultation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.section
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String section;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.prescription
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String prescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.syndrome_different_treatment
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String syndromeDifferentTreatment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.acupuncture_therapy
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String acupunctureTherapy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.syndrome_differentiation
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String syndromeDifferentiation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.prognosis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String prognosis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.introduction
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.thumbnail
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String thumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.epidemiology
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String epidemiology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.preventive_measure
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String preventiveMeasure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_symptom.picturepath
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    private String picturepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.inspection_items
     *
     * @return the value of miss_symptom.inspection_items
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getInspectionItems() {
        return inspectionItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.inspection_items
     *
     * @param inspectionItems the value for miss_symptom.inspection_items
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setInspectionItems(String inspectionItems) {
        this.inspectionItems = inspectionItems == null ? null : inspectionItems.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.t_other_therapies
     *
     * @return the value of miss_symptom.t_other_therapies
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String gettOtherTherapies() {
        return tOtherTherapies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.t_other_therapies
     *
     * @param tOtherTherapies the value for miss_symptom.t_other_therapies
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void settOtherTherapies(String tOtherTherapies) {
        this.tOtherTherapies = tOtherTherapies == null ? null : tOtherTherapies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.common_diseases
     *
     * @return the value of miss_symptom.common_diseases
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getCommonDiseases() {
        return commonDiseases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.common_diseases
     *
     * @param commonDiseases the value for miss_symptom.common_diseases
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setCommonDiseases(String commonDiseases) {
        this.commonDiseases = commonDiseases == null ? null : commonDiseases.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.t_preventive_nursing
     *
     * @return the value of miss_symptom.t_preventive_nursing
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String gettPreventiveNursing() {
        return tPreventiveNursing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.t_preventive_nursing
     *
     * @param tPreventiveNursing the value for miss_symptom.t_preventive_nursing
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void settPreventiveNursing(String tPreventiveNursing) {
        this.tPreventiveNursing = tPreventiveNursing == null ? null : tPreventiveNursing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.syndrome
     *
     * @return the value of miss_symptom.syndrome
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getSyndrome() {
        return syndrome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.syndrome
     *
     * @param syndrome the value for miss_symptom.syndrome
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setSyndrome(String syndrome) {
        this.syndrome = syndrome == null ? null : syndrome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.data_reference
     *
     * @return the value of miss_symptom.data_reference
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getDataReference() {
        return dataReference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.data_reference
     *
     * @param dataReference the value for miss_symptom.data_reference
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setDataReference(String dataReference) {
        this.dataReference = dataReference == null ? null : dataReference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.chinese_medicine
     *
     * @return the value of miss_symptom.chinese_medicine
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getChineseMedicine() {
        return chineseMedicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.chinese_medicine
     *
     * @param chineseMedicine the value for miss_symptom.chinese_medicine
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setChineseMedicine(String chineseMedicine) {
        this.chineseMedicine = chineseMedicine == null ? null : chineseMedicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.pathogeny
     *
     * @return the value of miss_symptom.pathogeny
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getPathogeny() {
        return pathogeny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.pathogeny
     *
     * @param pathogeny the value for miss_symptom.pathogeny
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setPathogeny(String pathogeny) {
        this.pathogeny = pathogeny == null ? null : pathogeny.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.pathogenesis
     *
     * @return the value of miss_symptom.pathogenesis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getPathogenesis() {
        return pathogenesis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.pathogenesis
     *
     * @param pathogenesis the value for miss_symptom.pathogenesis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setPathogenesis(String pathogenesis) {
        this.pathogenesis = pathogenesis == null ? null : pathogenesis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.dialectical_points
     *
     * @return the value of miss_symptom.dialectical_points
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getDialecticalPoints() {
        return dialecticalPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.dialectical_points
     *
     * @param dialecticalPoints the value for miss_symptom.dialectical_points
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setDialecticalPoints(String dialecticalPoints) {
        this.dialecticalPoints = dialecticalPoints == null ? null : dialecticalPoints.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.symptom_analysis
     *
     * @return the value of miss_symptom.symptom_analysis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getSymptomAnalysis() {
        return symptomAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.symptom_analysis
     *
     * @param symptomAnalysis the value for miss_symptom.symptom_analysis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setSymptomAnalysis(String symptomAnalysis) {
        this.symptomAnalysis = symptomAnalysis == null ? null : symptomAnalysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.common_chinese_medicine
     *
     * @return the value of miss_symptom.common_chinese_medicine
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getCommonChineseMedicine() {
        return commonChineseMedicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.common_chinese_medicine
     *
     * @param commonChineseMedicine the value for miss_symptom.common_chinese_medicine
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setCommonChineseMedicine(String commonChineseMedicine) {
        this.commonChineseMedicine = commonChineseMedicine == null ? null : commonChineseMedicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.t_common_syndrome_types
     *
     * @return the value of miss_symptom.t_common_syndrome_types
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String gettCommonSyndromeTypes() {
        return tCommonSyndromeTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.t_common_syndrome_types
     *
     * @param tCommonSyndromeTypes the value for miss_symptom.t_common_syndrome_types
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void settCommonSyndromeTypes(String tCommonSyndromeTypes) {
        this.tCommonSyndromeTypes = tCommonSyndromeTypes == null ? null : tCommonSyndromeTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.symptom_origin
     *
     * @return the value of miss_symptom.symptom_origin
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getSymptomOrigin() {
        return symptomOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.symptom_origin
     *
     * @param symptomOrigin the value for miss_symptom.symptom_origin
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setSymptomOrigin(String symptomOrigin) {
        this.symptomOrigin = symptomOrigin == null ? null : symptomOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.task_json
     *
     * @return the value of miss_symptom.task_json
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getTaskJson() {
        return taskJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.task_json
     *
     * @param taskJson the value for miss_symptom.task_json
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setTaskJson(String taskJson) {
        this.taskJson = taskJson == null ? null : taskJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.inspect
     *
     * @return the value of miss_symptom.inspect
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getInspect() {
        return inspect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.inspect
     *
     * @param inspect the value for miss_symptom.inspect
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setInspect(String inspect) {
        this.inspect = inspect == null ? null : inspect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.diagnosi
     *
     * @return the value of miss_symptom.diagnosi
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getDiagnosi() {
        return diagnosi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.diagnosi
     *
     * @param diagnosi the value for miss_symptom.diagnosi
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setDiagnosi(String diagnosi) {
        this.diagnosi = diagnosi == null ? null : diagnosi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.differential_diagnosis
     *
     * @return the value of miss_symptom.differential_diagnosis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getDifferentialDiagnosis() {
        return differentialDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.differential_diagnosis
     *
     * @param differentialDiagnosis the value for miss_symptom.differential_diagnosis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setDifferentialDiagnosis(String differentialDiagnosis) {
        this.differentialDiagnosis = differentialDiagnosis == null ? null : differentialDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.clinical_significance
     *
     * @return the value of miss_symptom.clinical_significance
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getClinicalSignificance() {
        return clinicalSignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.clinical_significance
     *
     * @param clinicalSignificance the value for miss_symptom.clinical_significance
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setClinicalSignificance(String clinicalSignificance) {
        this.clinicalSignificance = clinicalSignificance == null ? null : clinicalSignificance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.daily_nursing
     *
     * @return the value of miss_symptom.daily_nursing
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getDailyNursing() {
        return dailyNursing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.daily_nursing
     *
     * @param dailyNursing the value for miss_symptom.daily_nursing
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setDailyNursing(String dailyNursing) {
        this.dailyNursing = dailyNursing == null ? null : dailyNursing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.attention_matter
     *
     * @return the value of miss_symptom.attention_matter
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getAttentionMatter() {
        return attentionMatter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.attention_matter
     *
     * @param attentionMatter the value for miss_symptom.attention_matter
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setAttentionMatter(String attentionMatter) {
        this.attentionMatter = attentionMatter == null ? null : attentionMatter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.influence_factor
     *
     * @return the value of miss_symptom.influence_factor
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getInfluenceFactor() {
        return influenceFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.influence_factor
     *
     * @param influenceFactor the value for miss_symptom.influence_factor
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setInfluenceFactor(String influenceFactor) {
        this.influenceFactor = influenceFactor == null ? null : influenceFactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.consultation
     *
     * @return the value of miss_symptom.consultation
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getConsultation() {
        return consultation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.consultation
     *
     * @param consultation the value for miss_symptom.consultation
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setConsultation(String consultation) {
        this.consultation = consultation == null ? null : consultation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.section
     *
     * @return the value of miss_symptom.section
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getSection() {
        return section;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.section
     *
     * @param section the value for miss_symptom.section
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setSection(String section) {
        this.section = section == null ? null : section.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.prescription
     *
     * @return the value of miss_symptom.prescription
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getPrescription() {
        return prescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.prescription
     *
     * @param prescription the value for miss_symptom.prescription
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setPrescription(String prescription) {
        this.prescription = prescription == null ? null : prescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.syndrome_different_treatment
     *
     * @return the value of miss_symptom.syndrome_different_treatment
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getSyndromeDifferentTreatment() {
        return syndromeDifferentTreatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.syndrome_different_treatment
     *
     * @param syndromeDifferentTreatment the value for miss_symptom.syndrome_different_treatment
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setSyndromeDifferentTreatment(String syndromeDifferentTreatment) {
        this.syndromeDifferentTreatment = syndromeDifferentTreatment == null ? null : syndromeDifferentTreatment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.acupuncture_therapy
     *
     * @return the value of miss_symptom.acupuncture_therapy
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getAcupunctureTherapy() {
        return acupunctureTherapy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.acupuncture_therapy
     *
     * @param acupunctureTherapy the value for miss_symptom.acupuncture_therapy
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setAcupunctureTherapy(String acupunctureTherapy) {
        this.acupunctureTherapy = acupunctureTherapy == null ? null : acupunctureTherapy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.syndrome_differentiation
     *
     * @return the value of miss_symptom.syndrome_differentiation
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getSyndromeDifferentiation() {
        return syndromeDifferentiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.syndrome_differentiation
     *
     * @param syndromeDifferentiation the value for miss_symptom.syndrome_differentiation
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setSyndromeDifferentiation(String syndromeDifferentiation) {
        this.syndromeDifferentiation = syndromeDifferentiation == null ? null : syndromeDifferentiation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.prognosis
     *
     * @return the value of miss_symptom.prognosis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getPrognosis() {
        return prognosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.prognosis
     *
     * @param prognosis the value for miss_symptom.prognosis
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setPrognosis(String prognosis) {
        this.prognosis = prognosis == null ? null : prognosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.introduction
     *
     * @return the value of miss_symptom.introduction
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.introduction
     *
     * @param introduction the value for miss_symptom.introduction
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.thumbnail
     *
     * @return the value of miss_symptom.thumbnail
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.thumbnail
     *
     * @param thumbnail the value for miss_symptom.thumbnail
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.epidemiology
     *
     * @return the value of miss_symptom.epidemiology
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getEpidemiology() {
        return epidemiology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.epidemiology
     *
     * @param epidemiology the value for miss_symptom.epidemiology
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setEpidemiology(String epidemiology) {
        this.epidemiology = epidemiology == null ? null : epidemiology.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.preventive_measure
     *
     * @return the value of miss_symptom.preventive_measure
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getPreventiveMeasure() {
        return preventiveMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.preventive_measure
     *
     * @param preventiveMeasure the value for miss_symptom.preventive_measure
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setPreventiveMeasure(String preventiveMeasure) {
        this.preventiveMeasure = preventiveMeasure == null ? null : preventiveMeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_symptom.picturepath
     *
     * @return the value of miss_symptom.picturepath
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public String getPicturepath() {
        return picturepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_symptom.picturepath
     *
     * @param picturepath the value for miss_symptom.picturepath
     *
     * @mbg.generated Sat Apr 27 19:22:50 CST 2019
     */
    public void setPicturepath(String picturepath) {
        this.picturepath = picturepath == null ? null : picturepath.trim();
    }
}