package com.med.info.domain;

public class Miss_medical_companyWithBLOBs extends Miss_medical_company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical_company.business_scope
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String businessScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical_company.history
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String history;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical_company.company_introduction
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String companyIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical_company.brand_product
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String brandProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical_company.honor
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String honor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical_company.achievements
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String achievements;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical_company.news
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String news;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miss_medical_company.task_json
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    private String taskJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical_company.business_scope
     *
     * @return the value of miss_medical_company.business_scope
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical_company.business_scope
     *
     * @param businessScope the value for miss_medical_company.business_scope
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical_company.history
     *
     * @return the value of miss_medical_company.history
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getHistory() {
        return history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical_company.history
     *
     * @param history the value for miss_medical_company.history
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setHistory(String history) {
        this.history = history == null ? null : history.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical_company.company_introduction
     *
     * @return the value of miss_medical_company.company_introduction
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getCompanyIntroduction() {
        return companyIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical_company.company_introduction
     *
     * @param companyIntroduction the value for miss_medical_company.company_introduction
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setCompanyIntroduction(String companyIntroduction) {
        this.companyIntroduction = companyIntroduction == null ? null : companyIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical_company.brand_product
     *
     * @return the value of miss_medical_company.brand_product
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getBrandProduct() {
        return brandProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical_company.brand_product
     *
     * @param brandProduct the value for miss_medical_company.brand_product
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setBrandProduct(String brandProduct) {
        this.brandProduct = brandProduct == null ? null : brandProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical_company.honor
     *
     * @return the value of miss_medical_company.honor
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical_company.honor
     *
     * @param honor the value for miss_medical_company.honor
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setHonor(String honor) {
        this.honor = honor == null ? null : honor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical_company.achievements
     *
     * @return the value of miss_medical_company.achievements
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getAchievements() {
        return achievements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical_company.achievements
     *
     * @param achievements the value for miss_medical_company.achievements
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setAchievements(String achievements) {
        this.achievements = achievements == null ? null : achievements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical_company.news
     *
     * @return the value of miss_medical_company.news
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getNews() {
        return news;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical_company.news
     *
     * @param news the value for miss_medical_company.news
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setNews(String news) {
        this.news = news == null ? null : news.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miss_medical_company.task_json
     *
     * @return the value of miss_medical_company.task_json
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public String getTaskJson() {
        return taskJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miss_medical_company.task_json
     *
     * @param taskJson the value for miss_medical_company.task_json
     *
     * @mbg.generated Sat Nov 24 19:57:07 CST 2018
     */
    public void setTaskJson(String taskJson) {
        this.taskJson = taskJson == null ? null : taskJson.trim();
    }
}